<script type="text/javascript">
$(window).load(function() {
	$('#slider').nivoSlider({pauseTime:7e3,animSpeed:500,direction:'left',effect:'fade',directionNav:false,pauseOnHover:true});
});
</script>
<div class="Slide">
	<div class="slider-wrapper theme-default">
		<div class="ribbon"></div>
		<div id="slider" class="nivoSlider">
			<img src="<?= $this->baseUrl('/shop/img/slide3.jpg'); ?>" alt="Slide 3"
				title="Sony Xperia T Noir" /> <img
				src="<?= $this->baseUrl('/shop/img/slide1.jpg'); ?>" alt="Slide 1"
				title="Apple iPad 4 Retina Wifi et 3G 16Go Noir" /> <img
				src="<?= $this->baseUrl('/shop/img/slide2.jpg'); ?>" alt="Slide 2"
				title="Google Galaxy Nexus 16 Go Noir" />
		</div>
	</div>
</div>
<!--
<?php //if(count($this->vols) > 0) {?>
<div class="Block1">
	<div class="HeadBlock">Nouveautés</div>
	<div class="contentBLock1">
		<?php
		//foreach ($this->vols as $vol)
			//echo $this->action('bloc','produit','Shop',array('id_vol'=>$vol->id_vol, 'numero_ligne'=>$vol->numero_ligne));
		?>
	</div>
</div>-->
<?php //}
 if(count($this->vols1) > 0) {
	?>
<div class="Block1">
	<div class="HeadBlock">Top ventes</div>
	<div class="contentBLock1">
		<?php
		foreach ($this->vols1 as $vol)
			//echo $this->action('bloc','produit','Shop',array('id_vol'=>$vol->id_vol, 'numero_ligne'=>$vol->numero_ligne));
		?>
	</div>
</div>
<?php } ?>

