<h3 align="center">Informations sur le vol <?php echo $this->infosVol['idVol'];?> de la ligne <?php echo $this->infosVol['numeroLigne'];?></h3>
<br />
<br />
<table>
	<tr><td>Identifiant du vol: </td><td><?php echo $this->infosVol['idVol']?></td></tr>
	<tr><td>Numéro de la ligne: </td><td><?php echo $this->infosVol['numeroLigne']?></td></tr>
	<tr><td>Date de départ: </td><td><?php echo $this->infosVol['dateDepart']?></td></tr>
	<tr><td>Date d'arrivée: </td><td><?php echo $this->infosVol['dateArrivee']?></td></tr>
	<tr><td>Heure de départ: </td><td><?php echo $this->infosVol['heureDepart']?></td></tr>
	<tr><td>Heure d'arrivée: </td><td><?php echo $this->infosVol['heureArrivee']?></td></tr>
	<tr><td>Aéroport de départ: </td><td><?php echo $this->infosVol['aeroportDepart']?></td></tr>
	<tr><td>Aéroport d'arrivé: </td><td><?php echo $this->infosVol['aeroportArrivee']?></td></tr>
	<tr><td>Nom du pilote: </td><td><?php echo $this->infosVol['nomPilote']?></td></tr>
	<tr><td>Nom du co-pilte: </td><td><?php echo $this->infosVol['nomCoPilote']?></td></tr>
	<tr><td>Nom de l'avion: </td><td><?php echo $this->infosVol['nomAvion']?></td></tr>
	<tr><td>Tarif du vol:</td><td><?php echo $this->infosVol['tarif']?></td></tr>
</table>
<div align="center"><a href="/planning/listevol/date/<?php echo $this->timestamp;?>">Retour au planning</a></div>