<br /><br />
<table class="tableHeader">
	<tr>
		<td class="tdLienNextPrec"><a href="/planning/liste-vol/date/<?php echo $this->timestampPrec;?>">Jour précédent</a></td><td class="tdCenterDate"><span><?php echo $this->laDate;?></span></td><td class="tdLienNextPrec"><a href="/planning/liste-vol/date/<?php echo $this->timestampNext;?>">Jour suivant</a></td>
	</tr>
</table>

<?php
	if(count($this->paginator) != 0){
?>
	<table class="tableListeVol">
		<tr>
			<th>Numéro de ligne</th>
			<th>Aéroport de départ</th>
			<th>Heure de départ</th>
			<th>Aéroport d'arrivée</th>
			<th>Heure d'arrivée</th>
			<th>Options</th>
		</tr>
	<?php 
			foreach($this->paginator as $value){
				
				$error = ($value['error']) ? 'style="background-color:red;"' : '';
				
				if($value['options'] != 'Consulter')
					$lien = '/planning/planifier-vol/date/'.$value['date_depart'].'/numeroligne/'.$value['numero_ligne'].'';
				else
					$lien = '/vol/fiche-vol/ligne/'.$value['numero_ligne'].'/vol/'.$value['idVol'].'/';
				
				echo '
				<tr '.$error.'>
					<td>'.$value['numero_ligne'].'</td>
					<td><span class="spanAcronyme" title="'.$value['nom_aeroport_origine'].'">'.$value['aeroport_origine'].'</span></td>
					<td>'.$value['heure_depart'].'</td>
					<td><span class="spanAcronyme" title="'.$value['nom_aeroport_arrivee'].'">'.$value['aeroport_arrivee'].'</span></td>
					<td>'.$value['heure_arrivee'].'</td>
					<td><a href="'.$lien.'">'.$value['options'].'</a></td>
				</tr>';	
				
			}
	?>
</table>
<?php 
	}
	else{
		echo 'Aucun vol pour ce jour.';
	}
?>
<br />
<br />
<?php echo $this->paginationControl($this->paginator, 'Sliding', 'pagination.phtml'); ?>
<br />
<br />
<?php if(count($this->tabAeroportAstreinte) != 0){?>
<table class="tableAstreinte">
	<tr><th>Planification d'un équipage d'astreinte</th><th class="thOption">Options</th></tr>
	<?php 
		foreach($this->tabAeroportAstreinte as $aeroport => $value){
			echo '
			<tr>
				<td class="tdAeroport">'.$value['nom'].'</td>
				<td class="tdAeroportOption"><a href="/planning/planifier-astreinte/idaeroport/'.$aeroport.'/date/'.$value['date'].'/nbvol/'.$value['nbvol'].'/">'.$value['option'].'</a></td>
			</tr>';
		}
	?>
</table>
<?php }?>
