<br /><br />
<table class="tableHeader">
	<tr>
		<td class="tdLienNextPrec"><a href="/planning/listevol/date/<?php echo $this->timestampPrec;?>">Jour précédent</a></td><td class="tdCenterDate"><span><?php echo $this->laDate;?></span></td><td class="tdLienNextPrec"><a href="/planning/listevol/date/<?php echo $this->timestampNext;?>">Jour suivant</a></td>
	</tr>
</table>

<?php
	if(sizeof($this->tabLigne) != 0){
?>
	<table class="tableListeVol">
		<tr>
			<th>Numéro de ligne</th>
			<th>Aéroport de départ</th>
			<th>Heure de départ</th>
			<th>Aéroport d'arrivée</th>
			<th>Heure d'arrivée</th>
			<th>Options</th>
		</tr>
	<?php 
			foreach($this->tabLigne as $value){
				echo '<tr>';
				echo '
					<td>'.$value['numero_ligne'].'</td>
					<td><span class="spanAcronyme" title="'.$value['nom_aeroport_origine'].'">'.$value['aeroport_origine'].'</span></td>
					<td>'.$value['heure_depart'].'</td>
					<td><span class="spanAcronyme" title="'.$value['nom_aeroport_arrivee'].'">'.$value['aeroport_arrivee'].'</span></td>
					<td>'.$value['heure_arrivee'].'</td>
					<td><a href="/planning/planificationvol/date/'.$value['date_depart'].'/numeroligne/'.$value['numero_ligne'].'/actions/'.$value['options'].'">'.$value['options'].'</a></td>';
						
				echo '</tr>';
			}
	?>
</table>
<?php 
	}
	else{
		echo 'Aucun vol pour ce jour.';
	}
?>

<div class="divLienRetour"><a href="/planning/planning/">Retour au planning</a></div>