<?php $produits = $this->produits; ?>
<div class="contenuSidebar">
	<div class="headSidebar">
		<span class="titleHeadSidebar"><a
			href="<?= $this->baseUrl('panier');?>">Mon Vol</a> </span>
	</div>
	<div id="contentSidebar">
		<div class="blockSidePanier">
			<?php if(count($produits) > 0) {?>
			<div class="nbProduitContentSidePanier">
				<a href="<?= $this->baseUrl('panier'); ?>"><b>Voir le panier</b></a>
			</div>
			<?php foreach($produits as $vol) { ?>
			<div class="ligneContentSidePanier">
				<!--<div class="photoContentSidePanier">
					<?php 
					//if (($produit[1]->photo1 != NULL) && (file_exists(APPLICATION_PATH.'/../public/shop/img/Produits/'.$produit[1]->photo1))) {
				//	$ImageSize = Application_Image_Tools::adaptationTailleImage(APPLICATION_PATH.'/../public/shop/img/Produits/'.$produit[1]->photo1,80,98); ?>
					<a href="<?//= $this->baseUrl('Article/'.$produit[3]);?>"><img
						src="<?//= $this->baseUrl('/shop/img/Produits/Thumbnails/'.$produit[1]->photo1); ?>"
						width="<?//= $ImageSize[0]; ?>px" height="<//= $ImageSize[1]; ?>px">
					</a>
					<?php //} else { 
					//$ImageSize = Application_Image_Tools::adaptationTailleImage(APPLICATION_PATH.'/../public/shop/img/Produits/SmallNoPicture.png',80,98); ?>
					<img src="<?//=  $this->baseUrl('/shop/img/Produits/SmallNoPicture.png'); ?>"
						width="<?//= $ImageSize[0]; ?>px" height="<?//= $ImageSize[1]; ?>px">
					<?php // }?>
				</div>-->
				<div class="contentSidePanier" onClick="window.location='<?= $this->baseUrl('itineraire/'.$vol[1]->numero_ligne."_".$vol[1]->id_vol); ?>'">
					<ul>
						<label><b>Départ :</b></label>
						<li><?= $vol[1]->aeroportDepart;?></li>
						<li><?= $vol[1]->pays_Depart;?></li>
						<?php $Date = new Zend_Date($vol[1]->date_depart,'dd-MM-yy')?>
						<?php $jours = array('1'=>'Lundi', '2'=>'Mardi', '3' => 'Mercredi', '4' => 'Jeudi', '5' => 'Vendredi', '6' => 'Samedi', '7' => 'Dimanche');?>
						<?php $mois = array('01'=>'Janvier', '02'=>'Fevrier', '03' => 'Mars', '04' => 'Avril', '05' => 'Mai', '06' => 'Juin', '07' => 'Juillet', '08' => 'Aout', '09' => 'Septembre', '10' => 'Octobre', '11' => 'Novembre', '12' => 'Decembre');?>
						<?php $jourTexte = $jours[$Date->get('e')]; ?>
						<?php $moisTexte = $mois[$Date->get('MM')]; ?>
						<li><?= $jourTexte." ".$Date->get('dd')." ".$moisTexte;?></li>
						<li><?= $vol[1]->heure_depart;?></li>
					</ul>
					<ul>
						<label><b>Arrivée :</b></label>
						<li><?= $vol[1]->aeroportArrivee;?></li>
						<li><?= $vol[1]->pays_Arrive;?></li>
						<?php $Date1 = new Zend_Date($vol[1]->date_arrivee,'dd-MM-yy')?>
						<?php $jourTexte1 = $jours[$Date1->get('e')]; ?>
						<?php $moisTexte1 = $mois[$Date1->get('MM')]; ?>
						<li><?= $jourTexte1." ".$Date1->get('dd')." ".$moisTexte1;?></li>
						<li><?= $vol[1]->heure_arrivee;?></li>
					</ul>
					<div>
						<div><label><b>Nombre de reservation : </b></label><span><b><?= $vol[2];?> </b></span></div>
						<div><label><b>Prix pour une place : </b></label><span><b><?= $vol[4].'€'; ?></b></span></div>
					</div>
					<div id="iconeRemoveContentSidePanier">
						<a href="<?= $this->baseUrl('panier/'.$vol[1]->numero_ligne."_".$vol[1]->id_vol); ?>"
							id="removeContentSidePanier"><span>Supprimer</span> </a>
					</div>
				</div>
			</div>
			<?php } ?>
			<div id="sousTotalSidePanier">
				Total du vol : <b><?=$this->sousTotal." €";?> </b>
			</div>
			<?php } else {?>
			<div class="videSidePanier">Votre panier est vide.</div>
			<?php } ?>
		</div>
	</div>
</div>
