<?php $produits = $this->produits; ?>
<?php if($produits != NULL) {?>
<div class="contenuSidebar" style="border-bottom: 1px solid #E3E3E3;">
	<div class="headSidebar">
		<span class="titleHeadSidebar"><a
			href="<?= $this->baseUrl('top_ventes');?>">Top Ventes</a> </span>
	</div>
	<div id="contentSidebar">
		<div class="blockTopVentes">
			<?php
			$i =0;
			$cheminPublic ='public/shop';

			foreach ($produits as $produit)
			{
				?>
			<div class="ligneContentSidePanier"
			<?= ($i == 2) ? "style='border-bottom : none;'" : "";?>>
				<div class="photoContentSidePanier">
					<?php 
					if (($produit[0]->photo1 != NULL) && (file_exists(APPLICATION_PATH.'/../'.$cheminPublic.'/img/Produits/Thumbnails/'.$produit[0]->photo1))) {
										$ImageSize = Application_Image_Tools::adaptationTailleImage(APPLICATION_PATH.'/../'.$cheminPublic.'/img/Produits/'.$produit[0]->photo1,80,98); ?>
					<a href="<?= $this->baseUrl('Article/'.$produit[1]);?>"><img
						src="<?= $this->baseUrl('shop/img/Produits/Thumbnails/'.$produit[0]->photo1);?>"
						width="<?= $ImageSize[0]; ?>px" height="<?= $ImageSize[1]; ?>px">
					</a>
					<?php } else { 
					$ImageSize = Application_Image_Tools::adaptationTailleImage(APPLICATION_PATH.'/../'.$cheminPublic.'/img/Produits/SmallNoPicture.png',80,98); ?>
					<img
						src="<?= $this->baseUrl('shop/img/Produits/SmallNoPicture.png'); ?>"
						width="<?= $ImageSize[0]; ?>px" height="<?= $ImageSize[0]; ?>px">
					<?php }?>
				</div>
				<div class="contentSidePanier">
					<div>
						<a href="<?= $this->baseUrl('Article/'.$produit[1]);?>"><?=$produit[0]->designation; ?>
						</a>
					</div>
					<div>
						<?= $produit[0]->prix.'€'; ?>
					</div>
				</div>
			</div>
			<?php 	
			$i++;
			}
			?>
		</div>
	</div>
</div>
<?php } ?>