<?php $reservation = $this->reservation;?>
<?php $paiement = $this->paiement; ?>
<?php $client = $this->client; ?>
<?php $adresse = $this->adresse; ?>

<h2>
	Commande n°
	<?=$reservation->id_reservation; ?>
	-
	<?= ($reservation->is_valid) ? "Validé" : "En attente"; ?>
</h2>
<div class="Block">
	<div class="HeadBlock">Information sur la commande</div>
	<div class="contentBLock">
		<div class="rowBlock1">
			<div>Date de commande :</div>
			<div>
				Le
				<?= date("d/m/y à H:i",strtotime($reservation->date)); ?>
			</div>
		</div>
		<div class="rowBlock1">
			<div>Paiement par :</div>
			<div>
				<b><?= $paiement->libelle; ?> </b>
			</div>
		</div>
		<div class="rowBlock1">
			<div>Montant total :</div>
			<div>
				<?= $reservation->montant."€"; ?>
			</div>
		</div>
		<div class="rowBlock1">
			<div>Statut :</div>
			<div>
				<?php 	if($reservation->is_valid){?>
				<span id='LivreOk'>Validé</span>
				<?php }else { ?>
				<span id='LivreNok'>En attente</span>
				<?php }?>
			</div>
		</div>
		<?php //if ($reservation->commentaire != NULL) {?>
		<!--<div class="rowBlock1">
			<div>Commentaire :</div>
			<div>
				<?//= $reservation->commentaire;?>
			</div>
		</div>-->
		<?php //} ?>
	</div>
</div>
<div class="Block">
	<div class="HeadBlock">Information sur le client</div>
	<div class="contentBLock">
		<?php if ($client == NULL) { ?>
		<div class="rowBlock1">
			<div>Le client s'est désinscrit du site.</div>
		</div>
		<?php } else { ?>
		<div class="rowBlock1">
			<div>Nom :</div>
			<div>
				<?= $client->nom;?>
			</div>
		</div>
		<div class="rowBlock1">
			<div>Prénom :</div>
			<div>
				<?= $client->prenom;?>
			</div>
		</div>
		<div class="rowBlock1">
			<div>Email :</div>
			<div>
				<?= $client->mail;?>
			</div>
		</div>
		<div class="rowBlock1">
			<div>Login :</div>
			<div>
				<?= $client->login;?>
			</div>
		</div>
		<div class="rowBlock1">
			<div>Date d'inscription :</div>
			<div>
				<?= date("d/m/y à H:i",strtotime($client->date)); ?>
			</div>
		</div>
		<?php } ?>
	</div>
</div>
<div class="Block">
	<div class="HeadBlock">Adresse de facturation</div>
	<div class="contentBLock">
		<?php if ($adresse == NULL){?>
		<div class="rowBlock1">
			<div>L'adresse n'existe plus.</div>
		</div>
		<?php } else {?>
		<div class="rowBlock1">
			<?= $client->prenom." ".$client->nom; ?>
		</div>
		<div class="rowBlock1">
			<?= $adresse->adresse; ?>
		</div>
		<div class="rowBlock1">
			<?= $adresse->code_postal.", ".$adresse->ville; ?>
		</div>
		<div class="rowBlock1">
			<?= $adresse->pays; ?>
		</div>
		<?php }?>
	</div>
</div>
<div class="Block">
	<div class="HeadBlock">Information sur le vol</div>
	<div class="contentBLock">
		<?php if(true) { ?>
		<?php $TableVol = new Vol();
		$vol = $TableVol->find($reservation->id_vol,$reservation->numero_ligne)->current(); ?>
		<table id="tableau2">
			<thead>
				<tr class="Head">
					<th class="designationInfoProduit">Vol</th>
					<th class="designationInfoProduit">Ligne</th>
					<th class="quantiteRInfoProduit">Nombre de réservations</th>
					<th class="prixUInfoProduit">Prix unitaire</th>
					<th class="PrixTInfoProduit">Prix Total</th>
				</tr>
			</thead>
			<tbody>
				<tr class="<?= $this->cycle(array("Odd", "Even"))->next();?>">
					<?php if($vol != NULL) { ?>
					<td><a
						href="<?= $this->baseUrl('/vol/fiche-vol/ligne/'.$vol->numero_ligne.'/vol/'.$vol->id_vol); ?>"
						class="idInfoProduit" target="_blank"><?= $vol->id_vol;?> </a>
					</td>
					<td><a
						href="<?= $this->baseUrl('/vol/fiche-vol/ligne/'.$vol->numero_ligne.'/vol/'.$vol->id_vol); ?>"
						class="designationInfoProduit" target="_blank"><?= $vol->numero_ligne;?>
					</a>
					</td>
					<td><a
						href="<?= $this->baseUrl('/vol/fiche-vol/ligne/'.$vol->numero_ligne.'/vol/'.$vol->id_vol); ?>"
						class="quantiteligneProduit" target="_blank"><?=  $reservation->nbreservation; ?>
					</a>
					</td>
					<td><a
						href="<?= $this->baseUrl('/vol/fiche-vol/ligne/'.$vol->numero_ligne.'/vol/'.$vol->id_vol); ?>"
						class="quantiteRInfoProduit" target="_blank"> <?php if($vol->tarif_effectif == 0) echo $vol->tarif; else echo $vol->tarif_effectif; ?>€
					</a>
					</td>
					<td><a
						href="<?= $this->baseUrl('fiche_produit_admin/').$produit->id_produit; ?>"
						class="PrixTInfoProduit" target="_blank"><?= $reservation->montant." €";?>
					</a>
					</td>
					<?php } else {?>
					<td colspan="6"><span><b> Le vol a été supprimé </b> </span>
					</td>
					<?php } ?>
				</tr>
				<tr class="Odd">
					<td colspan="4"><span class="nom_total"><b>Montant Total</b> </span>
					</td>
					<td><span class="prix_total"><b><?= $reservation->montant." €"; ?>
						</b> </span></td>
				</tr>
			</tbody>
		</table>
		<?php } else {?>
		Le vol a été supprimé
		<?php } ?>
	</div>
</div>
<div class="Block" id="underline">
	<div class="contentBLock">
		<div class="rowBlock">
			<div>
				<?php if($reservation->is_valid){?>
				<form
					action="<?= $this->baseUrl('Shop/commande/envoye/is_valid/non/id/'.$reservation->id_reservation); ?>"
					method="get">
					<input type="submit" value="Marquer comme Refusé">
				</form>
				<?php }else { ?>
				<form
					action="<?= $this->baseUrl('Shop/commande/envoye/is_valid/oui/id/'.$reservation->id_reservation); ?>"
					method="get">
					<input type="submit" value="Marquer comme Validé">
				</form>
				<?php }?>
			</div>
		</div>
	</div>
</div>
<div id="page-retour">
	<a href="javascript:window.history.go(-1);" id="link_color"><small><<</small>
		Retour</a>
</div>

