<h2>Catalogue des reservations</h2>
<?php 
foreach($this->messages as $message)
	echo $message;
?>
<?php if($this->paginator->count() > 0) {?>

<table class="liste">
	<thead>
		<tr class="Head">
			<?php 
			echo $this->HeadId;
			echo $this->HeadLigne;
			echo $this->HeadVol;
			echo $this->HeadClient;
			echo $this->HeadQuantite;
			echo $this->HeadMontant;
			echo $this->HeadDate;
			echo $this->HeadEtat;
			?>
			<th></th>
		</tr>
	</thead>
	<tbody>
		<?php
		$i = 0;
		foreach ($this->paginator as $reservation)
		{
$i++;?>
		<tr class="<?= $this->cycle(array("Odd", "Even"))->next();?>">
			<td><a
				href="<?= $this->baseUrl('fiche_commande/').$reservation->id_reservation; ?>"
				class="idLigneCommande"><?= $reservation->id_reservation; ?> </a>
			</td>
			<td><a
				href="<?= $this->baseUrl('fiche_commande/').$reservation->id_reservation; ?>"
				class="idLigneCommande"><?= $reservation->numero_ligne; ?> </a>
			</td>
			<td><a
				href="<?= $this->baseUrl('fiche_commande/').$reservation->id_reservation; ?>"
				class="idLigneCommande"><?= $reservation->id_vol; ?> </a>
			</td>
			<td><a
				href="<?= $this->baseUrl('fiche_commande/').$reservation->id_reservation; ?>"
				class="nombreLigneCommande"><?= ($reservation->nom) ? $reservation->nom : "Inconnu"; 
				echo ($reservation->prenom) ? " ".$reservation->prenom : " Inconnu" ?>
			</a>
			</td>
			<td><a
				href="<?= $this->baseUrl('fiche_commande/').$reservation->id_reservation; ?>"
				class="quantiteLigneCommande"><?= $reservation->nbreservation; ?> </a>
			</td>
			<td><a
				href="<?= $this->baseUrl('fiche_commande/').$reservation->id_reservation; ?>"
				class="montantLigneCommande"><?= $reservation->montant."€"?> </a>
			</td>
			<td><?php
			$date = new Zend_Date($reservation->date,Zend_Date::DATETIME);
			$now = new Zend_Date(Zend_Date::now());
			$ecart = new Zend_Date($now->getTimestamp() - $date->getTimestamp(),Zend_Date::TIMESTAMP);
			$ecart->subHour('1');
			?> <a
				href="<?= $this->baseUrl('fiche_commande/').$reservation->id_reservation; ?>"
				class="dateLigneCommande" id="date_heure"><?= $ecart->get(Zend_Date::TIMES)?></a> 
				</td>
			<td><a
				href="<?= $this->baseUrl('fiche_commande/'.$reservation->id_reservation.'/'); ?>"
				class="montantLigneCommande"
				title="<?= ($reservation->is_valid) ? 'Marqué comme En Attente' : 'Marqué comme Validé'; ?>">
					<?php if($reservation->is_valid) { ?> <span style="color: green">Validé</span>
					<?php } else {?> <span style="color: red">En attente</span> <?php } ?>
			</a>
			</td>
		</tr>
		<?php }?>
	</tbody>
</table>
<?= $this->pagination; ?>
<?php } else {?>
<div class="CommandeLivre">Toutes les commandes sont livrées</div>
<?php } ?>
