<h2>Catalogue des reservations</h2>
<?php 
foreach($this->messages as $message)
	echo $message;
?>
<div id="texteDroite2">
	<?php if($this->livre){?>
	<a href="<?= $this->baseUrl('liste_commandes/livre');?>">Afficher
		toutes les commandes</a>
	<?php } else {?>
	<a href="<?= $this->baseUrl('liste_commandes');?>">Afficher uniquement
		les commandes non livrés</a>
	<?php } ?>
</div>
<?php if($this->paginator->count() > 0) {?>

<table class="liste">
	<thead>
		<tr class="Head">
			<?php 
			/*echo $this->HeadId;
			 echo $this->HeadNom;
			echo $this->HeadPrenom;
			echo $this->HeadNombre;
			echo $this->HeadMontant;
			echo $this->HeadDate;
			echo $this->HeadLivre;*/
			?>
			<th></th>
		</tr>
	</thead>
	<tbody>
		<?php
		foreach ($this->paginator as $reservation)
					{?>
		<tr class="<?= $this->cycle(array("Odd", "Even"))->next();?>">
			<td><a
				href="<?= $this->baseUrl('fiche_commande/').$reservation->id_reservation; ?>"
				class="idLigneCommande"><?= $reservation->id_reservation; ?> </a>
			</td>
			<td><a
				href="<?= $this->baseUrl('fiche_commande/').$reservation->id_reservation; ?>"
				class="nombreLigneCommande"><?= $reservation->numero_ligne; ?> </a>
			</td>
			<td><a
				href="<?= $this->baseUrl('fiche_commande/').$reservation->id_reservation; ?>"
				class="nombreLigneCommande"><?= $reservation->id_vol; ?> </a>
			</td>
			<td><a
				href="<?= $this->baseUrl('fiche_commande/').$reservation->id_reservation; ?>"
				class="nomLigneCommande"><?= ($reservation->nom) ? $reservation->nom : "Inconnu"; ?>
			</a>
			</td>
			<td><a
				href="<?= $this->baseUrl('fiche_commande/').$reservation->id_reservation; ?>"
				class="prenomLigneCommande"><?= ($reservation->prenom) ? $reservation->prenom : "Inconnu"; ?>
			</a>
			</td>
			<td><a
				href="<?= $this->baseUrl('fiche_commande/').$reservation->id_reservation; ?>"
				class="montantLigneCommande"><?= ($reservation->tarif_effectif == 0) ? $reservation->tarif."€" : $reservation->tarif_effectif."€"; ?></a>
			</td>
			<td><a
				href="<?= $this->baseUrl('fiche_commande/').$reservation->id_reservation; ?>"
				class="dateLigneCommande"><?= date("d/m/y à H:i",strtotime($reservation->date));?>
			</a>
			</td>
			<td><a
				href="<?//= $this->baseUrl('livre_commande/'.$reservation->id_reservation.'/'); ?><?//= ($reservation->Islivre) ? 'nonlivre' : 'livre'; ?>"
				class="boutonConfigCommande"
				title="<?//= ($reservation->Islivre) ? 'Marqué comme non livré' : 'Marqué comme livré'; ?>"></a>
		
		</tr>
		<?php }?>
	</tbody>
</table>
<?= $this->pagination; ?>
<?php } else {?>
<div class="CommandeLivre">Toutes les commandes sont livrées</div>
<?php } ?>