<h2>Catalogue des reservations</h2>
<?php 
foreach($this->messages as $message)
	echo $message;
?>
<?php if($this->paginator->count() > 0) {?>

<table class="liste">
	<thead>
		<tr class="Head">
			<?php 
			echo $this->HeadId;
			echo $this->HeadVol;
			echo $this->HeadLigne;
			echo $this->HeadClient;
			echo $this->HeadQuantite;
			echo $this->HeadMontant;
			echo $this->HeadDate;
			echo $this->HeadEtat;
			?>
			<th></th>
		</tr>
	</thead>
	<tbody>
		<?php
		$i = 0;
		foreach ($this->paginator as $reservation)
		{
$i++;?>
		<tr class="<?= $this->cycle(array("Odd", "Even"))->next();?>">
			<td><a
				href="<?= $this->baseUrl('fiche_commande/').$reservation->id_reservation; ?>"
				class="idLigneCommande"><?= $reservation->id_reservation; ?> </a>
			</td>
			<td><a
				href="<?= $this->baseUrl('fiche_commande/').$reservation->id_reservation; ?>"
				class="idLigneCommande"><?= $reservation->numero_ligne; ?> </a>
			</td>
			<td><a
				href="<?= $this->baseUrl('fiche_commande/').$reservation->id_reservation; ?>"
				class="idLigneCommande"><?= $reservation->id_vol; ?> </a>
			</td>
			<td><a
				href="<?= $this->baseUrl('fiche_commande/').$reservation->id_reservation; ?>"
				class="nombreLigneCommande"><?= ($reservation->nom) ? $reservation->nom : "Inconnu"; 
				echo ($reservation->prenom) ? " ".$reservation->prenom : " Inconnu" ?>
			</a>
			</td>
			<td><a
				href="<?= $this->baseUrl('fiche_commande/').$reservation->id_reservation; ?>"
				class="quantiteLigneCommande"><?= $reservation->nbreservation; ?> </a>
			</td>
			<td><a
				href="<?= $this->baseUrl('fiche_commande/').$reservation->id_reservation; ?>"
				class="montantLigneCommande"><?= $reservation->montant."€"?> </a>
			</td>
			<td><?php $dateDebut = new Zend_Date($reservation->date,'yyyy-MM-dd-HH-mm-ss');?>
				<?php //$dateNow = Zend_Date::now()->get('yyyy-MM-dd-HH-mm-ss'); ?>
				<?php $dateNow = new Zend_Date(); 
				//	echo $dateNow->get('HH:mm'),"<br>"; ?> <?php //$dateEcart = new Zend_Date("0000-00-00-02-00-00",'yyyy-MM-dd-HH-mm-ss');
			 //echo $dateEcart->get('HH:mm'),"<br>";?> <?php $dateNow->subHour($dateDebut)->subMinute($dateDebut); ?>
				<?php //echo $dateNow; ?> <?php //$dateEcart->subHour($dateNow)->subMinute($dateNow);?>
				<?php //$seconde = ($dateEcart->get('HH')*3600) + ($dateEcart->get('mm')*60) ?>
				<a
				href="<?= $this->baseUrl('fiche_commande/').$reservation->id_reservation; ?>"
				class="dateLigneCommande"><?= $dateNow->get('HH:mm');?> </a>
			</td>
			<td><a
				href="<?= $this->baseUrl('fiche_commande/'.$reservation->id_reservation.'/'); ?><?//= ($reservation->Islivre) ? 'nonlivre' : 'livre'; ?>"
				class="montantLigneCommande"
				title="<?= ($reservation->is_valid) ? 'Marqué comme non livré' : 'Marqué comme livré'; ?>">
					<?php if($reservation->is_valid) { 
						?> <span style="color: green">Validé</span> <?php } else {?> <span
					style="color: red">En attente</span> <?php } ?>
			</a>
		
		</tr>
		<?php }?>
	</tbody>
</table>
<?= $this->pagination; ?>
<?php } else {?>
<div class="CommandeLivre">Toutes les commandes sont livrées</div>
<?php } ?>
