<?php echo $this->doctype('HTML5');?>
<html>
<head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
<?php 
echo $this->headLink()->appendStylesheet('/css/style.css');
?>
<title><?php 
echo $this->escape($this->title);
$form = $this->formLogin;
?>
</title>
</head>
<body>
<div id="pere">
<div id="header"></div>
	<div id="login_connect">
		<div id="logo_connect"></div>
		<form method="<?php echo $form->getMethod() ?>"
		action="<?php echo $form->getAction();?>">
		<div>
			<div>
				<?php $form->getElement("login")->getDecorator('label')->setOption('tag', null); ?>
				<?php echo $form->login->renderLabel();?>
				<?php echo $form->login->renderViewHelper();?>
			</div>
		</div>
		<div>
			<div>
				<div>
					<?php $form->getElement("password")->getDecorator('label')->setOption('tag', null); ?>
					<?php echo $form->password->renderLabel();?>
					<?php echo $form->password->renderViewHelper();?>
				</div>
			</div>
		</div>
		<div>
			<div>
				<div>
					<?php echo $form->submit->renderViewHelper();?>
				</div>
			</div>
		</div>
</form>
	</div>
	<div id="footer"></div>
</div>
</body>
</html>

