<h3 class="h3DRH">Ajouter un service</h3>
<?php echo $this->action('ajouter-service', 'drh');?>
<br /><br />
<h3 class="h3DRH">Consulter les services</h3>
<div class="DivErreurForm MessageContentModifier"></div>
<table class="tableService">
	<tr>
		<?php 
			echo $this->libelle;
		?>
		<th style="width:70px;">Options</th>
	</tr>
	<?php 
		foreach($this->services as $service){
			echo '<tr class="'.$this->cycle(array("Odd", "Even"))->next().' service-'.$service['id_service'].'">';
			
				echo '<td class="tdLibelleService updateService"><div onclick="CreationInput('.$service['id_service'].', \''.addslashes($service['libelle_service']).'\', \'service\');">'.stripslashes($service['libelle_service']).'</div><form style="display:none;margin-top:10px;" method="post" onsubmit="AjaxModifierLibelle('.$service['id_service'].', \''.addslashes($service['libelle_service']).'\', \'service\', \''.$this->order.'\', '.$this->page.');return false;"><input type="text" name="modifier" size="70" value="'.stripslashes($service['libelle_service']).'"/></form></td>';
				echo '<td class="tdOptionService"><div onclick="CreationInput('.$service['id_service'].', \''.addslashes($service['libelle_service']).'\', \'service\');" class="icone_modifier_ligne updateService"></div></td>';
			echo '</tr>';
		}
	?>
</table>
<br />
<br />
<?php echo $this->paginationControl($this->services, 'Sliding', 'pagination.phtml', array('param' => $this->param)); ?>