<div class="pagination">
<div class="pagination-center">
	<!-- First page link -->
	<?php //if (isset($this->previous)): ?>
	<!--<a href="<?php //echo $this->url(array('page' => $this->first)); ?>">Début</a> |
        <?php //else: ?>
                <span class="disabled">Début</span> |-->
	<?php //endif; ?>

	<!-- Previous page link -->

	<?php if (isset($this->previous)): ?>
	<a href="<?= $this->url(array('page' => $this->previous)); ?>">
		<span class="enabled"><< Précedent</span></a>
	<?php else: ?>
	<span class="disabled"><< Précedent</span>
	<?php endif; ?>
	<!-- Numbered page links -->
	<?php foreach ($this->pagesInRange as $page): ?>
	<?php if ($page != $this->current): ?>
	<a href="<?= $this->url(array('page' => $page)); ?>"><span class="numero"><?= $page; ?></span>
	</a>
	<?php else: ?>
	<span class="numero_enabled"><?= $page; ?></span>
	<?php endif; ?>
	<?php endforeach; ?>

	<!-- Next page link -->
	<?php if (isset($this->next)): ?>
	<a href="<?= $this->url(array('page' => $this->next)); ?>"><span class="enabled">Suivant >></span></a>
	<?php else: ?>
	<span class="disabled">Suivant >></span>
	<?php endif; ?>

	<!-- Last page link -->
	<?php //if (isset($this->next)): ?>
	<!--<a href="<? //echo $this->url(array('page' => $this->last)); ?>">Fin</a>
        <?php //else: ?>
            <span class="disabled">Fin</span>
        <?php //endif; ?>
        Page <?php //echo $this->current; ?>/<?php //echo $this->last; ?>-->
</div></div>
