<?= $this->doctype('HTML5');?>
<html>
<head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
<?php 
$this->headScript()->appendFile($this->baseUrl('js/fonctions.js'));
$this->headLink()->appendStylesheet($this->baseUrl('css/style.css'));
$this->headLink()->headLink( array( 'rel' => 'favicon',
		'href' => $this->baseUrl( 'favicon.ico' ),
		'type' => 'image/x-icon' ));
echo $this->headLink();
echo $this->headScript();
?>
<script type="text/javascript">
$(window).load(function() {
	$('#slider').nivoSlider();
});
</script>
<?php
$TableParametre = new Shop_Model_Parametre();
$Parametre = $TableParametre->fetchRow();
?>
<title><?= $Parametre->site. " | ".$this->escape($this->title); ?></title>
</head>
<body>
	<div id="wrapper">
		<?= $this->partial('partials/header.phtml');?>
		<div id="page">
			<div id="HomeContent">
			<div class="breadCrumb">
				Vous êtes ici : <?= $this->navigation()->breadcrumbs()->setMinDepth(0)->setLinkLast(true)->setSeparator(' / ');?>
			</div>
				<?//= $this->layout()->content; ?>
			</div>
		</div>
		<?= $this->partial('partials/footer.phtml');?>
	</div>
</body>
</html>
