<?php 
foreach($this->messages as $message)
	echo $message;
?>
<?php if(count($this->paginator) > 0){ ?>
<h2>Liste des avions pour la maintenance</h2>
<table class="table_consulter-ligne">
	<thead>
		<tr id="TableHead">
			<?php 
			echo $this->Id;
			echo $this->Type;
			echo $this->Places;
			echo $this->Heures;
			echo $this->Revision;
			echo $this->NbVol;
			echo $this->Disponibilite;
			?>
			<th class="emplacement_icone"></th>
		</tr>
	</thead>
	<tbody>
		<?php 
	foreach ($this->paginator as $avion){ ?>
		<tr class="<?php echo $this->cycle(array("Odd", "Even"))->next();?>">
			<td class="ligne"><a
				href="<?php echo $this->baseUrl('maintenance/fiche-avion/id/').$avion['id_avion']; ?>">
					<?php echo $avion['id_avion']; ?>
			</a></td>
			<td class="ligne"><a
				href="<?php echo $this->baseUrl('maintenance/fiche-avion/id/').$avion['id_avion']; ?>">
					<?php echo $avion['libelle']; ?>
			</a></td>
			<td class="ligne"><a
				href="<?php echo $this->baseUrl('maintenance/fiche-avion/id/').$avion['id_avion']; ?>">
					<?php echo $avion['total_heure_vol']; ?>
			</a></td>
			<td class="ligne"><a
				href="<?php echo $this->baseUrl('maintenance/fiche-avion/id/').$avion['id_avion']; ?>">
					<?php if($avion['diff'] <= 15) 
						echo "<span style='color:red'><b>".round($avion['diff'],2)."</b></span>";
					else
						echo '<span style="color:green">'.round($avion['diff'],2).'</span>'; ?>
			</a></td>
			<td class="ligne"><a
				href="<?php echo $this->baseUrl('maintenance/fiche-avion/id/').$avion['id_avion']; ?>">
					<?php echo $avion['nbVol']; ?>
			</a></td>
			<td class="ligne"><a
				href="<?php echo $this->baseUrl('maintenance/fiche-avion/id/').$avion['id_avion']; ?>">
					<?php echo ($avion['disponibilite_avion'])? "Disponible" : "En maintenance"; ?>
			</a></td>
			<td><?php if($avion['disponibilite_avion'] == "0"){?><a
				href="<?php echo $this->baseUrl('maintenance/intervention/id/').$avion['id_avion']; ?>"
				class="icone_modifier_maintenance" title="Voir les interventions"></a><?php }?>
			</td>
		</tr>
		<?php } ?>
	</tbody>
</table>
<?php 
echo $this->paginationControl($this->paginator, 'Sliding', 'pagination.phtml',array("param"=>$this->param));
} else {?>
<div class="noLine">Aucun avion</div>
<?php } ?>



