<?php 
foreach($this->messages as $message)
	echo $message;
?>
<?php $avion = $this->avion; ?>
<?php $typeAvion = $avion->findParentRow('TypeAvion'); ?>
<h1>
	Fiche de l'avion
	<?php echo $avion->id_avion;?>
</h1>
<div class="fiche-vol">
	<fieldset>
		<legend>Informations sur l'avion</legend>
		<div class="infoLigneRow">
			<label for="numero">Numéro de l'avion : </label>
			<div class="" id="numero">
				<?php echo $avion->id_avion;?>
			</div>
		</div>
		<div class="infoLigneRow">
			<label for="aeroport_origine">Modèle de l'avion : </label>
			<div class="" id="aeroport_origine">
				<?php echo $typeAvion->libelle; ?>
			</div>
		</div>
		<div class="infoLigneRow">
			<label for="aeroport_depart">Nombre de places : </label>
			<div class="" id="aeroport_depart">
				<?php echo $avion->nb_places;?>
				places
			</div>
		</div>
		<div class="infoLigneRow">
			<label for="aeroport_arrive">Nombre d'heures total : </label>
			<div class="" id="aeroport_arrive">
				<?php echo $avion->total_heure_vol;?>
				h
			</div>
		</div>
		<div class="infoLigneRow">
			<label for="heure_depart">Nombre d'heures avant Grande révision : </label>
			<div class="" id="heure_depart">
				<?php echo $avion->nb_heures_gd_revision;?>
				h
			</div>
		</div>
		<?php $total = 0;?>
		<div class="infoLigneRow">
			<label>Durée des prochains vols :</label>
		</div>
		<?php foreach($this->vols as $vol) {?>
		<div class="infoLigneRow">
			<?php $date = new Zend_Date($vol->date_depart,'yyyy-MM-dd')?>
			<label> - Le <?=$date->get('dd/MM/yyyy'); ?>
			</label>
			<div>
				<?php $dateDepart = new Zend_Date($vol->date_depart.' '.$vol->heure_depart);
				$dateArrivee = new Zend_Date($vol->date_arrivee.' '.$vol->heure_arrivee);
				$diff = $dateArrivee->sub($dateDepart)->toValue()/3600;
				$total += $diff;
				?>
				<?php echo round($diff,2);?>
				h
			</div>
		</div>
		<?php } ?>
		<div class="infoLigneRow">
			<label for="total_heure">Total des heures restantes dans 4 semaines : </label>
			<div class="" id="total_heure">
				<?php echo round($avion->nb_heures_gd_revision-$total,2)." h"; ?>
			</div>
		</div>
		<div class="infoLigneRow">
			<label for="heure_arrivee">Disponibilité : </label>
			<div class="" id="heure_arrivee">
				<?php echo ($avion->disponibilite_avion)? "Disponible" : "En maintenance"; ?>
			</div>
		</div>
	</fieldset>
	<fieldset>
		<legend>Informations sur le modèle de l'avion</legend>
		<div class="infoLigneRow">
			<label for="numero">Numéro du modèle : </label>
			<div class="" id="numero">
				<?php echo $typeAvion->id_type_avion;?>
			</div>
		</div>
		<div class="infoLigneRow">
			<label for="numero">Libellé du modèle : </label>
			<div class="" id="numero">
				<?php echo $typeAvion->libelle;?>
			</div>
		</div>
		<div class="infoLigneRow">
			<label for="aeroport_origine">Rayon d'action : </label>
			<div class="" id="aeroport_origine">
				<?php echo $typeAvion->rayon_action; ?>
				m
			</div>
		</div>
		<div class="infoLigneRow">
			<label for="aeroport_depart">Longueur de décollage : </label>
			<div class="" id="aeroport_depart">
				<?php echo $typeAvion->longueur_decollage;?>
				m
			</div>
		</div>
		<div class="infoLigneRow">
			<label for="aeroport_arrive">longueur d'atterrissage : </label>
			<div class="" id="aeroport_arrive">
				<?php echo $typeAvion->longueur_atterrissage;?>
				m
			</div>
		</div>
	</fieldset>
	<fieldset>
		<legend>Informations maintenances</legend>
		<?php $maintenances = $this->maintenance; ?>
		<?php if($maintenances->count()) 
		{?>
		<?php foreach($maintenances as $maintenance) : ?>
		<?php $dateDebut = new Zend_Date($maintenance->date_prevue,'dd-MM-yy'); ?>
		<?php $dateFin = new Zend_Date($maintenance->fin_prevue,'dd-MM-yy'); ?>

		<div class="infoLigneRow">
			<label for="numero">Id de la maintenance : </label>
			<div class="" id="numero">
				<?php echo $maintenance->id_maintenance;?>
			</div>
		</div>
		<div class="infoLigneRow">
			<label for="aeroport_origine">Type de maintenance : </label>
			<div class="" id="aeroport_origine">
				<?php $dateTemp = new Zend_Date($maintenance->date_prevue,'dd-MM-yy'); ?>
				<?php $dateTemp->addDay(10); ?>
				<?php if($dateTemp == $dateFin) echo "Grosse révision (10 jours)"; else echo "Petite révision (2 jours)" ?>
			</div>
		</div>
		<div class="infoLigneRow">
			<label for="aeroport_depart">Date de début : </label>
			<div class="" id="aeroport_depart">
				<?php echo $dateDebut->get('dd-MM-yyyy'); ?>
			</div>
		</div>
		<div class="infoLigneRow">
			<label for="aeroport_arrive">Date de fin : </label>
			<div class="" id="aeroport_arrive">
				<?php echo $dateFin->get('dd-MM-yyyy');?>
			</div>
		</div>
		<?php endforeach; 
		}?>
		<?php if(($this->maintenanceAvion->count()) || ($maintenances->count())) {?>
		<a
			href="<?= $this->baseUrl('maintenance/fiche-avion-maintenance/id/').$avion->id_avion ?>">Voir
			toutes les maintenances sur cet avion</a>
		<?php } else if($this->maintenanceAvion->count() == 0) {?>
		<div class="noLine">Il n'y a jamais eu de maintenance sur cet avion</div>
		<?php } ?>
	</fieldset>
</div>
<h2>Planifier une nouvelle maintenance :</h2>
<script type="text/javascript">
		$(document).ready(function(){
			$('#calendar').calendar({
				'nbSemaine' : 8,
				'link' : '/maintenance/ajouter-maintenance/id/<?= $avion->id_avion ?>/mode/<?=$this->mode; ?>/',
					'colorDate' : {
					4 : 'maintenanceAvion4',
					3 : 'maintenanceAvion3',
					2 : 'maintenanceAvion2',
					1 : 'maintenanceAvion1',
					0 : 'trWeek'
				},
				'infoDate' : {
					<?php
						$index = 0;
						foreach($this->datePlanning as $date){
							$index++;
							echo '\''.$date['date'].'\' : {\''.$date['texte'].'\' : '.$date['indexClass'].'}';
							if(count($this->datePlanning) != $index){
								echo ',';
							}
						}
					?>
				}
			});	
		});
	</script>
<br />
<div id="calendar"></div>
