<a href="<?php echo $this->baseUrl('maintenance/ajouter-avion'); ?>"><button>Ajouter un avion</button></a>
<a href="<?php echo $this->baseUrl('maintenance/consulter-avion'); ?>"><button>Consulter les avions</button></a>
<a href="<?php echo $this->baseUrl('maintenance/consulter-maintenance'); ?>"><button>Consulter les avions version maintenance</button></a>
<a href="<?php echo $this->baseUrl('maintenance/ajouter-modele-avion'); ?>"><button>Ajouter un type d'avion</button></a>
<a href="<?php echo $this->baseUrl('maintenance/consulter-modele-avion'); ?>"><button>Consulter les types d'avions</button></a>
<a href="<?php echo $this->baseUrl('maintenance/planning'); ?>"><button>Voir le planning</button></a>
