<script type="text/javascript">
$(document).ready(function(){
	$("input[name=Duree]").timepicker({
		hourGrid: 4,
		minuteGrid: 10,
		timeFormat: "hh:mm:ss t",
	});
});
</script>

<?php 
foreach($this->messages as $message)
	echo $message;
?>
<?php if(count($this->paginator) > 0){ ?>
<h2>Liste des interventions pour la maintenance</h2>
<?php echo $this->form; ?>
<table class="table_consulter-ligne">
	<thead>
		<tr id="TableHead">
			<th>Id</th>
			<th>Utilisateur</th>
			<th>Date</th>
			<th>Durée</th>
			<th>Commentaire</th>
		</tr>
	</thead>
	<tbody>
		<?php 
	foreach ($this->paginator as $inter){ ?>
		<tr class="<?php echo $this->cycle(array("Odd", "Even"))->next();?>">
			<td class="ligne"><?php echo $inter['id_intervention']; ?></td>
			<td class="ligne"><?php echo $inter['login']; ?></td>
			<td class="ligne"><?php echo $inter['date_effective']; ?></td>
			<td class="ligne"><?php echo $inter['duree_effective']; ?></td>
			<td class="ligne"><?php echo $inter['commentaire']; ?></td>
		</tr>
		<?php } ?>
	</tbody>
</table>
<?php 
echo $this->paginationControl($this->paginator, 'Sliding', 'pagination.phtml',array("param"=>$this->param));
} else {?>
<div class="noLine">Aucun avion</div>
<?php } ?>



