<?php $client = $this->client; ?>
<?php $adresse = $this->adresse; ?>
<?php $transport = $this->transport; ?>
<?php $paiement = $this->paiement; ?>
<?php $vol = $this->vol; ?>
<?php $form = $this->form;?>

<h2>Information de facturation et de livraison</h2>

<form method="<?= $form->getMethod() ?>"
	action="<?= $form->getAction();?>">
	<div class="Block">
		<div class="HeadBlock">
			<div class="titleHead">Information sur les produits</div>
			<div class="texteDroite">
				<a href="<?= $this->baseUrl('client/panier'); ?>">Editer</a>
			</div>
		</div>
		<div class="contentBLock">
			<table id="Total">
				<thead>
					<tr>
						<th class="designationInfoProduitClient">Vol</th>
						<th class="quantiteligneProduitClient">Reservation</th>
						<th class="prixUInfoProduitClient">Prix unitaire</th>
						<th class="PrixTInfoProduitClient">Prix Total</th>
					</tr>
				</thead>
				<tbody>
					<tr class="Even">
						<td class="designationInfoProduitClient1">
							<ul>
								<label>Départ :</label>
								<li><?= $vol[1]->aeroportDepart;?></li>
								<li><?= $vol[1]->pays_Depart;?></li>
								<?php $Date = new Zend_Date($vol[1]->date_depart,'dd-MM-yy')?>
								<?php $jours = array('1'=>'Lundi', '2'=>'Mardi', '3' => 'Mercredi', '4' => 'Jeudi', '5' => 'Vendredi', '6' => 'Samedi', '7' => 'Dimanche');?>
								<?php $mois = array('01'=>'Janvier', '02'=>'Fevrier', '03' => 'Mars', '04' => 'Avril', '05' => 'Mai', '06' => 'Juin', '07' => 'Juillet', '08' => 'Aout', '09' => 'Septembre', '10' => 'Octobre', '11' => 'Novembre', '12' => 'Decembre');?>
								<?php $jourTexte = $jours[$Date->get('e')]; ?>
								<?php $moisTexte = $mois[$Date->get('MM')]; ?>
								<li><?= $jourTexte." ".$Date->get('dd')." ".$moisTexte;?></li>
								<li><?= $vol[1]->heure_depart;?></li>
							</ul>
							<ul>
								<label>Arrivée :</label>
								<li><?= $vol[1]->aeroportArrivee;?></li>
								<li><?= $vol[1]->pays_Arrive;?></li>
								<?php $Date1 = new Zend_Date($vol[1]->date_arrivee,'dd-MM-yy')?>
								<?php $jourTexte1 = $jours[$Date1->get('e')]; ?>
								<?php $moisTexte1 = $mois[$Date1->get('MM')]; ?>
								<li><?= $jourTexte1." ".$Date1->get('dd')." ".$moisTexte1;?></li>
								<li><?= $vol[1]->heure_arrivee;?></li>
							</ul>
						</td>
						<td><span class="quantiteligneProduitClient" target="_blank"><?=  $vol[2]; ?>
						</span></td>
						<td><span class="prixUInfoProduitClient" target="_blank"><?= round($vol[4],2).' €';?>
						</span>
						</td>
						<td><span class="PrixTInfoProduitClient" target="_blank"><?= round(($vol[4] * $vol[2]),2).' €';?>
						</span></td>
					</tr>
					<tr class="montant-confirmation">
						<td colspan="3"><span class="nom_total">Montant Total</span>
						</td>
						<td><span class="prix_total"><?= round($this->montant,2).' €'; ?>
						</span></td>
					</tr>
				</tbody>
			</table>
		</div>
	</div>
	<div class="Block">
		<div class="HeadBlock">
			<div class="titleHead">Adresse de facturation</div>
			<div class="texteDroite">
				<a href="<?= $this->baseUrl('client/checkout-adresse'); ?>">Editer</a>
			</div>
		</div>
		<div class="contentBLock">
			<div class="contentSubContentInfoCompte">
				<div class="rowBlock">
					<?= $client->prenom." ".$client->nom; ?>
				</div>
				<div class="rowBlock">
					<?= $adresse['adresse']; ?>
				</div>
				<div class="rowBlock">
					<?= $adresse['code_postal'].", ".$adresse['ville']; ?>
				</div>
				<div class="rowBlock">
					<?= $adresse['pays']; ?>
				</div>
			</div>
		</div>
	</div>
	<div class="Block">
		<div class="HeadBlock">
			<div class="titleHead">Mode de paiement</div>
			<div class="texteDroite">
				<a href="<?= $this->baseUrl('client/checkout-mode-paiement'); ?>">Editer</a>
			</div>
		</div>
		<div class="contentBLock">
			<div class="contentSubContentInfoCompte">
				<div class="rowBlock">
					<?= $paiement['libelle']; ?>
				</div>
			</div>
		</div>
	</div>
	<!--<div class="Block">
		<div class="HeadBlock">Commentaire</div>
		<div class="contentBLock">
			<div class="contentSubContentInfoCompte">
				<div class="rowBlock3">
					<?php //$form->getElement("texte")->getDecorator('label')->setOption('tag', null); ?>
					<div>
						<label>Commentaire sur le vol (allergies, repas spéciaux ...) : </label>
					</div>
					<div>
						<?//= $form->texte->renderViewHelper();?>
					</div>
					<div>
						<?//= $form->texte->renderErrors();?>
					</div>
				</div>
			</div>
		</div>
	</div>-->
	<div class="Block" id="underline">
		<div class="contentBLock">
			<div class="rowBlock">
				<div>
					<? echo $form->confirmer->renderViewHelper();?>
				</div>
			</div>
		</div>
	</div>
</form>
