<?php if( isset($this->erreur)){ ?>
<?= $this->erreur;?>
<?php } ?>
<h2>Votre commande a bien été reçue.</h2>
<div class="commande_achever">
	<b>Merci de votre achat !</b>
	<div class="texte_commande_achever">
		Votre n° de commande est :
		<?= $this->numeroReservation; ?>
		.<BR> Vous allez recevoir un mail de confirmation avec les détails de
		votre commande. <BR> <b>Dans les deux heures, vous aurez une réponse
			si vos réservations sont acceptées ou non par notre service commercial.
			
			<BR>
			Si vos réservations sont acceptées, vous pourrez spécifier des commentaires liés au vol (problèmes medicaux, soins, alimentation ...) dans votre compte, dans la section Réservation.</b>
			
	</div>
</div>
<div>
	<a href="<?= $this->baseUrl('accueil'); ?>" id="link_color"><small><<</small>
		Retour à la page d'accueil</a>
</div>
