<div id="footer">
	<div id="adresse">
		<div>48 rue Rue Raspail</div>
		<div>02100 Saint-Quentin</div>
		<div>Tel : +03 23 62 89 59</div>
		<div>fax : +03 23 62 89 59</div>
	</div>
	<div id="sitemap">
		<div class="categorie">
			<div class="subCategorie1">
				<a href="<?= $this->baseUrl('/');?>"><b>Accueil</b> </a>
			</div>
			<div class="subCategorie1">
				<a href="<?= $this->baseUrl('compte');?>"><b>Compte</b> </a>
			</div>
			<div class="subCategorie1">
				<a href="<?= $this->baseUrl('menu');?>"><b>Administration</b> </a>
			</div>
		</div>
	</div>
	<div id="powered">
		Powered By <a href="mailto:johnny.cottereau@gmail.com">Johnny
			Cottereau</a> - © Copyright
		<?php echo date('Y');?>
	</div>
</div>
