<div id="footer">
	<div id="adresse">
		<div>48 rue Rue Raspail</div>
		<div>02100 Saint-Quentin</div>
		<div>Tel : +03 23 62 89 59</div>
		<div>fax : +03 23 62 89 59</div>
	</div>
	<div id="sitemap">
		<div class="categorie">
			<div class="subCategorie1">
				<a href="<?= $this->baseUrl('/');?>"><b>Accueil</b> </a>
			</div>
			<div class="subCategorie1">
				<a href="<?= $this->baseUrl('compte');?>"><b>Compte</b> </a>
			</div>
			<?php  if( (Zend_Auth::getInstance()->getIdentity()) && (isset(Zend_Auth::getInstance()->getIdentity()->id_service)) ) : ?>
			<div class="subCategorie1">
				<a href="<?= $this->baseUrl('liste_commandes');?>"><b>Administration</b> </a>
			</div>
			<?php endif; ?>
		</div>
	</div>
	<div id="powered">
		<p>Copyright INSSET Airlines - <?php echo date('Y');?></p>
			
	</div>
</div>
