<?php
$tableCategories = new Shop_Model_Categorie;
$tableSouscategorie = new Shop_Model_SousCategorie;
$categories = $tableCategories->fetchAll();
?>
<ul class="navigation">
	<li id="cat[0]"><a href="<?= $this->baseUrl('accueil'); ?>">Accueil</a>
	</li>
	<li id="cat[1]"><a href=" <?= $this->baseUrl('catalogue');?>">Catalogue</a>
	</li>
	<?php 
	$NomCat = new Application_Url();
	foreach($categories as $categorie)
	{
		$nomCategorie = $NomCat::Rewrite($categorie->libelle);
		$requete = $tableSouscategorie->select()->from($tableSouscategorie)->where("id_categorie=?",$categorie->id_categorie);
		$souscategories = $tableSouscategorie->fetchAll($requete);
		?>
	<li><a href="<?= $this->baseurl($nomCategorie); ?>"><div class="lienMenu">
				<span><?= $categorie->libelle; ?> </span>
				<?php if($souscategories != NULL) { ?>
				<div id='child'></div>
			</div> <?php } ?> </a>
		<ul class="sousNavigation">
			<?php 
			foreach ($souscategories as $souscategorie)
			{
				$nomSousCategorie = $NomCat::Rewrite($souscategorie->libelle);
				?>
			<li><a
				href="<?= $this->baseurl($nomCategorie.'/'.$nomSousCategorie);?> "><?= $souscategorie->libelle; ?>
			</a>
			</li>
			<?php 
			}
			?>
		</ul>
	</li>
	<?php 
	}
	?>
	<li id="last_menu1"><a href=" <?= $this->baseUrl('top_ventes');?>">Top
			Ventes</a>
	
	<li id="last_menu"><a href=" <?= $this->baseUrl('new');?>">Nouveautés</a>

</ul>
