<div id="sidebar">
	<div class="contenuSidebar" style="border-bottom: 1px solid #E3E3E3;">
		<div class="headSidebar">
			<span class="titleHeadSidebar">Une Question ?</span>
		</div>
		<div id="contentSidebar">
			<img src="<?= $this->baseUrl('/shop/img/call_we.jpg'); ?>">
		</div>
	</div>
	<?= $this->action('categorie','sidebar','Shop'); ?>
	<?= $this->action('panier','sidebar','Shop'); ?>
	<?= $this->action('top-ventes','sidebar','Shop'); ?> 

	<a href=""><img src="<?= $this->baseUrl('/shop/img/exclusivite.jpg'); ?>"> </a>
</div>

