<div id="sidebarPanel">
	<div class="contenuSidebar">
		<div class="headSidebar">
			<div class="titleHeadSidebar">Mon compte</div>
		</div>
		<div id="contentSidebar">
			<ul class="panel1">
			<li><a href="<?= $this->baseUrl('compte');?>"><div>Tableau de bord</div></a></li>
				<li><a href="<?= $this->baseUrl('information_compte');?>"><div>Informations
							du compte</div> </a></li>
				<li><a href="<?= $this->baseUrl('carnet_adresses');?>"><div>Carnet
							d'adresses</div> </a></li>
				<li><a href="<?= $this->baseUrl('mes_commandes');?>"><div>Mes
							Réservations</div> </a>
				</li>
			</ul>
		</div>
	</div>
</div>
