<?php 
$form = $this->form;
$vol = $this->vol;

$ligne = $vol->findParentRow('Ligne');

$AeroportDepart = $ligne->findParentRow('Aeroport','aeroport_depart');
$VilleDepart = $AeroportDepart->findParentRow('Ville');
$AeroportArrivee = $ligne->findParentRow('Aeroport','aeroport_arrivee');
$VilleArrivee = $AeroportArrivee->findParentRow('Ville');
?>
<input type="hidden" id="adresseDepart"
	value="<?= $AeroportDepart->adresse.", ".$VilleDepart->nom.", ".$VilleDepart->findParentRow('Pays')->nom; ?>"
	name="adresseDepart">
<input type="hidden" id="adresseArrivee"
	value="<?= $AeroportArrivee->adresse.", ".$VilleArrivee->nom.", ".$VilleArrivee->findParentRow('Pays')->nom; ?>"
	name="adresseArrivee">
<div class="subContentProduit">
	<h1>
		<?= "De ".$vol->aeroportDepart." (".$vol->pays_Depart.") à destination de ".$vol->aeroportArrivee." (".$vol->pays_Arrive.")"?>
	</h1>
	<?php if ($this->Nouveaute) {?>
	<div class="nouveaute"></div>
	<?php } ?>
	<div id="photosProduit">
		<div id="Map" class="Map-New-Ligne"></div>
	</div>
	<div id="detailProduit">
		<div id="priceProduit">
			<label>Prix : </label><span id="priceProduit2"> <?php if($vol->tarif_effectif == 0) echo $vol->tarif; else echo $vol->tarif_effectif;?>€
			</span>
		</div>
		<form method="<?= $form->getMethod() ?>"
			action="<?= $form->getAction();?>">
			<?= $form->id->renderViewHelper();?>
			<div class="quantiteProduit">
				<label class="quantiteLabel">Nombre de reservations : </label>
				<?= $form->quantite->renderViewHelper();?>
				<div>
					<label><?= $form->quantite->renderErrors();?> </label>
				</div>
			</div>
			<?php if(($vol->nb_places - $vol->nbreservations) <= 0) {?>
			<div class="enCours">Vol complet</div>
			<?php } else {?>
			<div class="ajout">
				<?= $form->ajouter->renderViewHelper();?>
			</div>
			<?php } ?>
		</form>
		<?php $sessionPanier = new Zend_Session_Namespace('panier');?>
		<?php if ( (isset($sessionPanier->content[$vol->id_vol])) && ($sessionPanier->content[$vol->id_vol] != NULL) ) { ?>
		<div class="panierProduit">
			<span id="already">Déjà ajouté au panier</span> <span><a
				href="<?= $this->baseUrl('client/panier'); ?>">Voir le panier</a> ou
				<a href="<?= $this->baseUrl('index/login'); ?>">Se connecter</a> </span>
		</div>
		<?php } ?>
		<div>
			<label class="DescBrefLabel">Description rapide : </label>
			<div class="DescBref">
				<div>
					<label>Départ : </label>
					<?= $vol->aeroportDepart;?>
				</div>
				<div>
					<label>Arrivée : </label>
					<?= $vol->aeroportDepart;?>
				</div>
			</div>
		</div>
	</div>
	<div class="DescProduit">
		<label class="DescLabel">Description du vol : </label>
		<div class="Desc">
			<div class="contenuSidebar">
				<div class="headSidebar">
					<span class="titleHeadSidebar"><a href="/panier">Départ</a> </span>
				</div>
				<div id="contentSidebar">
					<div class="blockSidePanier">
						<ul>
							<li><?= $vol->aeroportDepart;?></li>
							<li><?= $vol->pays_Depart;?></li>
							<li><?= $vol->date_depart;?></li>
							<li><?= $vol->heure_depart;?></li>
						</ul>
					</div>
				</div>
			</div>
			<div class="contenuSidebar">
				<div class="headSidebar">
					<span class="titleHeadSidebar"><a href="/panier">Arrivée</a> </span>
				</div>
				<div id="contentSidebar">
					<div class="blockSidePanier">
						<ul>
							<li><?= $vol->aeroportDepart;?></li>
							<li><?= $vol->pays_Arrive;?></li>
							<li><?= $vol->date_arrivee;?></li>
							<li><?= $vol->heure_arrivee;?></li>
						</ul>
					</div>
				</div>
			</div>
		</div>
	</div>
	<div class="diversProduit">
		<div class="print">
			<a onclick="window.print();return false;" href="#">Imprimer</a>
		</div>
	</div>
</div>
