<?php $form = $this->form; 
$cheminPublic = 'public/shop';
?>
<div class="subContentProduit">
	<h1>
		<?= $this->produit->designation;?>
	</h1>
	<?php if ($this->Nouveaute) {?>
	<div class="nouveaute"></div>
	<?php } ?>
	<div id="photosProduit">
		<div id="primaryPhotoProduit">
			<img
				src="<?= $this->baseUrl('/shop/img/Produits/'.$this->produit->photo1); ?>"
				id="big_photo">
		</div>
		<?php if((($this->produit->photo2 != NULL)||($this->produit->photo3 != NULL))  && (file_exists(APPLICATION_PATH.'/../'.$cheminPublic.'/img/Produits/Thumbnails/'.$this->produit->photo1))){ ?>
		<div class="secondariesPhotoProduit" id="first_photo">
			<img
				src="<?= $this->baseUrl('/shop/img/Produits/Thumbnails/'.$this->produit->photo1); ?>"
				id="primary_photo" onClick="AffichageImage(this);">
		</div>
		<?php } ?>
		<?php if(($this->produit->photo2 != NULL) && (file_exists(APPLICATION_PATH.'/../'.$cheminPublic.'/img/Produits/Thumbnails/'.$this->produit->photo2))) { ?>
		<div class="secondariesPhotoProduit">
			<img
				src="<?= $this->baseUrl('/shop/img/Produits/Thumbnails/'.$this->produit->photo2); ?>"
				id="secondary_photo" onClick="AffichageImage(this);">
		</div>
		<?php } 
		?>
		<?php if(($this->produit->photo3 != NULL) && (file_exists(APPLICATION_PATH.'/../'.$cheminPublic.'/img/Produits/Thumbnails/'.$this->produit->photo3))) { ?>
		<div class="secondariesPhotoProduit" id="third_photo">
			<img
				src="<?= $this->baseUrl('/shop/img/Produits/Thumbnails/'.$this->produit->photo3); ?>"
				id="third_photo" onClick="AffichageImage(this);">
		</div>
		<?php } ?>
	</div>
	<div id="detailProduit">
		<div id="priceProduit">
			<label>Prix : </label><span id="priceProduit2"><?= round($this->produit->prix,2)." €"; ?>
			</span>
		</div>
		<form method="<?= $form->getMethod() ?>"
			action="<?= $form->getAction();?>">
			<?= $form->id->renderViewHelper();?>
			<div class="quantiteProduit">
				<label class="quantiteLabel"> Quantité : </label>
				<?= $form->quantite->renderViewHelper();?>
				<div>
					<label><?= $form->quantite->renderErrors();?> </label>
				</div>
			</div>
			<?php if($this->produit->quantite <= 0) {?>
			<div class="enCours">En cours de réappovisionnement</div>
			<?php } else {?>
			<div class="ajout">
				<?= $form->ajouter->renderViewHelper();?>
			</div>
			<?php } ?>
		</form>
		<?php $sessionPanier = new Zend_Session_Namespace('panier');?>
		<?php if ( (isset($sessionPanier->content[$this->produit->id_produit])) && ($sessionPanier->content[$this->produit->id_produit] != NULL) ) { ?>
		<div class="panierProduit">
			<span id="already">Déjà ajouté au panier</span> <span><a
				href="<?= $this->baseUrl('client/panier'); ?>">Voir le panier</a> ou
				<a href="<?= $this->baseUrl('index/login'); ?>">Se connecter</a> </span>
		</div>
		<?php } ?>
		<div>
			<label class="DescBrefLabel">Description rapide : </label>
			<div class="DescBref">
				<?= $this->produit->descriptionBreve;?>
			</div>
		</div>
	</div>
	<div class="DescProduit">
		<label class="DescLabel">Description du produit : </label>
		<div class="Desc">
			<?= $this->produit->description; ?>
		</div>
	</div>
	<div class="diversProduit">
		<div class="print">
			<a onclick="window.print();return false;" href="#">Imprimer</a>
		</div>
	</div>
</div>
