<h2>Catalogue des vols</h2>
<?php 
$cheminPublic = 'shop/public';
foreach($this->messages as $message)
	echo $message;
?>
<?php if($this->paginator->count() > 0) {?>
<table class="liste">
	<thead>
		<tr class="Head">
			<?php 
			echo $this->HeadIdLigne;
			echo $this->HeadIdVol;
			echo $this->HeadAeroDepart;
			echo $this->HeadAeroArrive;
			echo $this->HeadDateDepart;
			echo $this->HeadDateArrivee;
			echo $this->HeadTotalPlaces;
			echo $this->HeadRestantePlaces;
			?>
		</tr>
	</thead>
	<tbody>
		<?php foreach ($this->paginator as $vol) { ?>
		<?php $DateDepart = new Zend_Date($vol->date_depart,'dd-MM-yy')?>
		<?php $DateArrivee = new Zend_Date($vol->date_arrivee,'dd-MM-yy')?>
		<tr class="<?= $this->cycle(array("Odd", "Even"))->next();?>">
			<td><a
				href="<?= $this->baseUrl('fiche_produit_admin/').$vol->numero_ligne."_".$vol->id_vol; ?>"
				class="idLigneVol"><?= $vol->numero_ligne; ?> </a>
			</td>
			<td><a
				href="<?= $this->baseUrl('fiche_produit_admin/').$vol->numero_ligne."_".$vol->id_vol; ?>"
				class="idLigneVol"><?= $vol->id_vol; ?> </a>
			</td>
			<td><a
				href="<?= $this->baseUrl('fiche_produit_admin/').$vol->numero_ligne."_".$vol->id_vol; ?>"
				class="designationAeroportVol"><?= $vol->aeroportDepart; ?> </a>
			</td>
			<td><a
				href="<?= $this->baseUrl('fiche_produit_admin/').$vol->numero_ligne."_".$vol->id_vol; ?>"
				class="designationAeroportVol"><?= $vol->aeroportArrivee; ?> </a>
			</td>
			<td><a
				href="<?= $this->baseUrl('fiche_produit_admin/').$vol->numero_ligne."_".$vol->id_vol; ?>"
				class="dateVol"><?=$DateDepart->get('dd-MM-yyyy'); ?> </a>
			</td>
			<td><a
				href="<?= $this->baseUrl('fiche_produit_admin/').$vol->numero_ligne."_".$vol->id_vol; ?>"
				class="dateVol"><?= $DateArrivee->get('dd-MM-yyyy'); ?> </a>
			</td>
			<td><a
				href="<?= $this->baseUrl('fiche_produit_admin/').$vol->numero_ligne."_".$vol->id_vol; ?>"
				class="quantiteVol"><?= ($vol->nb_places != NULL) ? $vol->nb_places : "NULL";    ?> </a>
			</td>
			<td><a
				href="<?= $this->baseUrl('fiche_produit_admin/').$vol->numero_ligne."_".$vol->id_vol; ?>"
				class="quantiteVol"><?= ($vol->nb_places != NULL) ? $vol->nb_places - $vol->nbreservations : "NULL";  ?>
			</a>
			</td>
		</tr>
		<?php }?>
	</tbody>
</table>
<?= $this->pagination; ?>
<?php } else {?>
Le catalogue des produits est vide
<?php } ?>