<h2>Catalogue des vols</h2>
<?php 
$cheminPublic = 'shop/public';
foreach($this->messages as $message)
	echo $message;
?>
<div id="mode_liste">
	<ul>
		<li><a
			href="<?php echo $this->baseUrl('liste_produit/Ligne_Asc/1/tous'); ?>">Afficher
				Tous les vols</a></li>
		<li><a
			href="<?php echo $this->baseUrl('liste_produit/Ligne_Asc/1/now_futur'); ?>">Afficher
				les vols en cours / futurs</a></li>
		<li><a
			href="<?php echo $this->baseUrl('liste_produit/Ligne_Asc/1/precedent'); ?>">Afficher
				les vols précedents</a></li>
		<li><a
			href="<?php echo $this->baseUrl('liste_produit/Ligne_Asc/1/attente'); ?>">Afficher
				les vols en attente de validation de temps de vol</a></li>
	</ul>
</div>

<?php if($this->paginator->count() > 0) {?>
<table class="liste">
	<thead>
		<tr class="Head">
			<?php 
			echo $this->HeadIdLigne;
			echo $this->HeadIdVol;
			echo $this->HeadAeroDepart;
			echo $this->HeadAeroArrive;
			echo $this->HeadDateDepart;
			echo $this->HeadDateArrivee;
			echo $this->HeadTotalPlaces;
			echo $this->HeadEtatPlaces;
			?>
		</tr>
	</thead>
	<tbody>
		<?php foreach ($this->paginator as $vol) { ?>
		<?php $DateDepart = new Zend_Date($vol->date_depart,'dd-MM-yy')?>
		<?php $DateArrivee = new Zend_Date($vol->date_arrivee,'dd-MM-yy')?>
		<tr class="<?= $this->cycle(array("Odd", "Even"))->next();?>">
			<td><a
				href="<?= $this->baseUrl('vol/fiche-vol/ligne/'.$vol->numero_ligne.'/vol/'.$vol->id_vol); ?>"
				class="idLigneVol"><?= $vol->numero_ligne; ?> </a>
			</td>
			<td><a
				href="<?= $this->baseUrl('vol/fiche-vol/ligne/'.$vol->numero_ligne.'/vol/'.$vol->id_vol); ?>"
				class="idLigneVol"><?= $vol->id_vol; ?> </a>
			</td>
			<td><a
				href="<?= $this->baseUrl('vol/fiche-vol/ligne/'.$vol->numero_ligne.'/vol/'.$vol->id_vol); ?>"
				class="designationAeroportVol"><?= $vol->aeroportDepart; ?> </a>
			</td>
			<td><a
				href="<?= $this->baseUrl('vol/fiche-vol/ligne/'.$vol->numero_ligne.'/vol/'.$vol->id_vol); ?>"
				class="designationAeroportVol"><?= $vol->aeroportArrivee; ?> </a>
			</td>
			<td><a
				href="<?= $this->baseUrl('vol/fiche-vol/ligne/'.$vol->numero_ligne.'/vol/'.$vol->id_vol); ?>"
				class="dateVol"><?=$DateDepart->get('dd-MM-yyyy'); ?> </a>
			</td>
			<td><a
				href="<?= $this->baseUrl('vol/fiche-vol/ligne/'.$vol->numero_ligne.'/vol/'.$vol->id_vol); ?>"
				class="dateVol"><?= $DateArrivee->get('dd-MM-yyyy'); ?> </a>
			</td>
			<td><a
				href="<?= $this->baseUrl('vol/fiche-vol/ligne/'.$vol->numero_ligne.'/vol/'.$vol->id_vol); ?>"
				class="quantiteVol"><?= ($vol->nb_places != NULL) ? $vol->nb_places - $vol->nbreservations : "NULL"; ?>
					/ <?= ($vol->nb_places != NULL) ? $vol->nb_places : "NULL"; ?> </a>
			</td>
			<td><a
				href="<?= $this->baseUrl('vol/fiche-vol/ligne/'.$vol->numero_ligne.'/vol/'.$vol->id_vol); ?>"
				class="etatVol"> <?php 
				if ($vol->is_arrive) { ?> <span style="color: green">Arrivé</span> <?php } else {
					if($vol->date_arrivee <= Zend_Date::now()->get('yyyy-MM-dd')) {
						?> <span style="color: red">En attente</span> <?php } else if(($vol->date_depart <= Zend_Date::now()->get('yyyy-MM-dd'))&& ($vol->date_arrivee >= Zend_Date::now()->get('yyyy-MM-dd'))) { ?>
					<span style="color: blue">En vol</span> <?php } 
				}?>
			</a>
			</td>
		</tr>
		<?php }?>
	</tbody>
</table>
<?= $this->pagination; ?>
<?php } else {?>
Le catalogue des vols est vide
<?php } ?>