<div class="optionPanel">
	<div>
		<a
			href="<?= $this->baseUrl('modifier_produit/').$this->id; ?>"
			class="boutonModifierProduit"> Modifier </a>
	</div>
	<div>
		<a
			href="<?= $this->baseUrl('statut_produit/').$this->id; ?>"
			class="boutonStatutProduit"> Changer statut </a>
	</div>
	<div>
		<a
			href="<?= $this->baseUrl('supprimer_produit/').$this->id; ?>"
			class="boutonSupprimerProduit"> Supprimer </a>
	</div>
</div>
<?php 
foreach($this->messages as $message)
	echo $message;
?>
<?= $this->action('fiche','produit','Shop',array('id'=>$this->id,'layout'=>true)); ?>
<div id="page-retour">
	<a href="<?= $_SERVER['HTTP_REFERER']; ?>" id="link_color"><small><<</small> Retour</a>
</div>