<h2>Éditer les informations du compte</h2>
<?php $client = $this->client;?>
<div class="optionPanel">
	<div>
		<a
			href="<?php echo $this->baseUrl('supprimer_client/').$client->id_client; ?>"
						class="boutonSupprimerProduit"> Supprimer </a>
	</div>
</div>
<?php $form = $this->form;?>
<?php  
if($this->message != NULL)
	echo $this->message;
?>
<form method="<?= $form->getMethod() ?>"
	action="<?= $form->getAction();?>">
	<div class="Block">
		<div class="HeadBlock">Information du compte</div>
		<div class="contentBLock">
			<div class="rowBlock">
				<?php $form->getElement("Identifiant")->getDecorator('label')->setOption('tag', null); 
				if($form->getElement('Identifiant')->hasErrors())
					$form->Identifiant->setAttrib('class','inputRequired');?>
				<div>
					<?= $form->Identifiant->renderLabel();?>
				</div>
				<div>
					<?= $form->Identifiant->renderViewHelper();?>
				</div>
				<div>
					<?= $form->Identifiant->renderErrors();?>
				</div>
			</div>
			<div class="rowBlock">
				<?php $form->getElement("nom")->getDecorator('label')->setOption('tag', null); 
				if($form->getElement('nom')->hasErrors())
					$form->nom->setAttrib('class','inputRequired');?>
				<div>
					<?= $form->nom->renderLabel();?>
				</div>
				<div>
					<?= $form->nom->renderViewHelper();?>
				</div>
				<div>
					<?= $form->nom->renderErrors();?>
				</div>
			</div>
			<div class="rowBlock">
				<?php $form->getElement("prenom")->getDecorator('label')->setOption('tag', null); 
				if($form->getElement('prenom')->hasErrors())
					$form->prenom->setAttrib('class','inputRequired');?>
				<div>
					<?= $form->prenom->renderLabel();?>
				</div>
				<div>
					<?= $form->prenom->renderViewHelper();?>
				</div>
				<div>
					<?= $form->prenom->renderErrors();?>
				</div>
			</div>
			<div class="rowBlock">
				<?php $form->getElement("mail")->getDecorator('label')->setOption('tag', null); 
				if($form->getElement('mail')->hasErrors())
					$form->mail->setAttrib('class','inputRequired');?>
				<div>
					<?= $form->mail->renderLabel();?>
				</div>
				<div>
					<?= $form->mail->renderViewHelper();?>
				</div>
				<div>
					<?= $form->mail->renderErrors();?>
				</div>
			</div>
			<div class="rowBlock">
				<?php $form->getElement("login")->getDecorator('label')->setOption('tag', null);
				if($form->getElement('login')->hasErrors())
					$form->login->setAttrib('class','inputRequired'); ?>
				<div>
					<?= $form->login->renderLabel();?>
				</div>
				<div>
					<?= $form->login->renderViewHelper();?>
				</div>
				<div>
					<?= $form->login->renderErrors();?>
				</div>
			</div>
		</div>
	</div>
	<div class="Block">
		<div class="HeadBlock">Modifier le mot de passe</div>
		<div class="contentBLock">
			<div class="rowBlock">
				<?php $form->getElement("passVisible")->getDecorator('label')->setOption('tag', null); 
				if($form->getElement('passVisible')->hasErrors())
					$form->passVisible->setAttrib('class','inputRequired');?>
				<div>
					<?= $form->passVisible->renderLabel();?>
				</div>
				<div>
					<?= $form->passVisible->renderViewHelper();?>
				</div>
				<div>
					<?= $form->passVisible->renderErrors();?>
				</div>
			</div>
		</div>
	</div>
	<div class="Block" id="underline">
		<div class="contentBLock">
			<div class="rowBlock">
				<div>
					<?= $form->Valider->renderViewHelper();?>
				</div>
			</div>
		</div>
	</div>
</form>
<div id="page-retour">
	<a href="<?= $_SERVER['HTTP_REFERER']; ?>" id="link_color"><small><<</small> Retour</a>
</div>