<script type="text/javascript">
	$(document).ready(function(){	
		$('#calendar').calendar({
			'nbSemaine' : 4, 
			'link' : '/planning/liste-vol/',
			'colorDate' : {
			//	1 : 'intervaltest',       	// La clé correspond à la valeur du tableau infoDate, la valeur correspond à la class CSS 		
				0 : 'trWeek'				// permettant de changer la couleur du jour
											// toujours mettre à la clé 0 une valeur par défaut (trWeek)
			},
			'infoDate' : { 	
			//	'01/02/2013' : {'plop' : 1},		//La clé correspond au jour, la seconde correspond au texte présent à l'intérieur de la case
			//	'16/01/2013' : {'plopy' : null},	//de ce jour et la valeur correspond à la clé du tablea ude couleur donnant sa class CSS
			//	'15/01/2013' : {'plop545' : 0}		//mettre null ou 0 pour colorer par défaut
			}
		});	
	});
</script>
<br />
<div id="calendar"></div>

<?php 
/**
 * 
 * Exemple de formattage du JavaScript en PHP
 *
	<script type="text/javascript">
		$(document).ready(function(){
			$('#calendar').calendar({
				'nbSemaine' : 4,
				'link' : '/planning/liste-vol/',
				'colorDate' : {
					1 : 'intervaltest',
					0 : 'trWeek'
				},
				'infoDate' : {
					<?php
						$index = 0;
						foreach($dates as $date){
							$index++;
							echo '\''.$date['date'].'\' : {\''.$date['texte'].'\' : '.$date['indexClass'].'}';
							if(count($dates) != $index){
								echo ',';
							}
						}
					?>
				}
			});	
		});
	</script> 
*/
?>