<?php $form = $this->form;?>
<?php 
if($this->message != NULL)
	echo $this->message;
?>
<h2>Ajouter une catégorie ou une sous-catégorie</h2>
<div class="textBlock">Vous pouvez ajouter une catégorie OU une sous-catégorie à la fois .</div>
<form method="<?= $form->getMethod() ?>"
	action="<?= $form->getAction();?>">
	<div class="Block">
		<div class="HeadBlock">
			<h3>Catégorie</h3>
		</div>
		<div class="contentBLock">
			<div class="rowBlock">
				<?php $form->getElement("newCategorie")->getDecorator('label')->setOption('tag', null); ?>
				<div>
					<?= $form->newCategorie->renderLabel();?>
				</div>
				<div>
					<?= $form->newCategorie->renderViewHelper();?>
				</div>
				<div>
					<?= $form->newCategorie->renderErrors();?>
				</div>
			</div>
		</div>
	</div>
	<div class="Block">
		<div class="HeadBlock">
			<h3>Sous-catégorie</h3>
		</div>
		<div class="contentBLock">
			<div class="rowBlock">
				<?php $form->getElement("categorie")->getDecorator('label')->setOption('tag', null); ?>
				<div>
					<?= $form->categorie->renderLabel();?>
				</div>
				<div>
					<?= $form->categorie->renderViewHelper();?>
				</div>
				<div>
					<?= $form->categorie->renderErrors();?>
				</div>
			</div>
			<div class="rowBlock">
				<?php $form->getElement("newSousCategorie")->getDecorator('label')->setOption('tag', null); ?>
				<div>
					<?= $form->newSousCategorie->renderLabel();?>
				</div>
				<div>
					<?= $form->newSousCategorie->renderViewHelper();?>
				</div>
				<div>
					<?= $form->newSousCategorie->renderErrors();?>
				</div>
			</div>
		</div>
	</div>
	<div class="Block" id="underline">
		<div class="contentBLock">
			<div class="BoutonCreateContent">
				<?= $form->Ajouter->renderViewHelper();?>
			</div>
		</div>
	</div>
</form>
