<?= $this->doctype('HTML5');?>
<html>
<head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
<?php 
$this->headScript()->appendFile($this->baseUrl('js/jquery-1.8.2.min.js'));
$this->headScript()->appendFile('http://code.jquery.com/jquery-1.7.1.min.js');
$this->headScript()->appendFile($this->baseUrl('js/jquery-ui-1.9.0.custom.min.js'));
$this->headScript()->appendFile($this->baseUrl('js/jquery-ui-sliderAccess.js'));
$this->headScript()->appendFile($this->baseUrl('js/jquery-ui-timepicker-addon.js'));
$this->headScript()->appendFile('http://maps.googleapis.com/maps/api/js?sensor=false&libraries=geometry');

$this->headScript()->appendFile($this->baseUrl('js/VolFonction.js'));
$this->headScript()->appendFile($this->baseUrl('shop/js/fonctions.js'));
$this->headScript()->appendFile($this->baseUrl('shop/js/jquery.nivo.slider.pack.js'));

$this->headLink()->appendStylesheet($this->baseUrl('css/jquery-ui-timepicker-addon.css'));
$this->headLink()->appendStylesheet($this->baseUrl('css/jquery-ui-1.8.23.css'));
$this->headLink()->appendStylesheet($this->baseUrl('shop/css/style.css'));
$this->headLink()->appendStylesheet($this->baseUrl('shop/css/Slide/styleSlide.css'));
$this->headLink()->appendStylesheet($this->baseUrl('shop/css/Slide/ThemeSlide.css'));
$this->headLink()->appendStylesheet($this->baseUrl('shop/css/Slide/nivo-slider.css'));




$this->headLink()->headLink( array( 'rel' => 'favicon',
		'href' => $this->baseUrl( 'shop/favicon.ico' ),
		'type' => 'image/x-icon' ));
echo $this->headLink();
echo $this->headScript();

$TableParametre = new Shop_Model_Parametre();
$Parametre = $TableParametre->fetchRow();
?>
<title><?= $Parametre->site. " | ".$this->escape($this->title); ?></title>
</head>
<body onload="initializeMap1();" >
	<div id="wrapper">
		<?= $this->partial('partials/header.phtml');?>
		<div id="page">
			<?= $this->partial('partials/sidebar.phtml');?>
			<div id="content">
			<div class="breadCrumb">
				Vous êtes ici : <?= $this->navigation()->breadcrumbs()->setMinDepth(0)->setLinkLast(true)->setSeparator(' / ');?>
			</div>
				<?= $this->layout()->content; ?>
			</div>
		</div>
		<?= $this->partial('partials/footer.phtml');?>
	</div>
</body>
</html>
