<?php echo $this->doctype('HTML5');?>
<html>
<head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
<?php 
echo $this->headLink()->appendStylesheet('/css/style.css');
?>
<title><?php 
echo $this->escape($this->title);
?>
</title>
</head>
<body>
<div id="pere">
<div id="header"></div>
	<div id="login_connect">
		<div id="logo_connect"></div>
		<form>
			<?php echo $this->action('login','auth'); ?>
		</form>
	</div>
	<div id="footer"></div>
</div>
</body>
</html>
