<?php echo $this->doctype('HTML5');?>
<html>
<head>
<meta name="viewport" content="initial-scale=1.0, user-scalable=no" />

<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
<?php 
$this->headLink()->appendStylesheet('/css/style.css');
$this->headScript()->prependFile('/js/jquery-ui-1.9.0.custom.min.js');
$this->headScript()->prependFile('/js/jquery-1.8.2.min.js');

echo $this->headScript();
echo $this->headLink();
$controller = Zend_Controller_Front::getInstance()->getRequest()->getControllerName();
?>
<title><?php echo $this->escape($this->title); ?>
</title>
</head>
<body <?php if ($controller=="vol") echo 'onload="initialisation()"'; ?>>
	<div id="pere">
		<div id="header">
			<div id="logo"></div>
			<div id="connect">
				<?php echo $this->partial('partials/identity.phtml'); ?>
			</div>
		</div>
		<div id="side_bar"></div>
		<div id="breadcrumbs">
			<?php echo $this->navigation()->breadcrumbs();?>
		</div>
		<nav>
			<?php echo $this->partial('partials/navigation.phtml'); ?>
		</nav>
		<?php echo $this->layout()->content; ?>

	</div>
	<div id="footer">
		<p>Copyright INSSET Airlines - 2012</p>
	</div>
</body>
</html>
