<?php echo $this->doctype('HTML5');?>
<html>
<head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
<?php 
echo $this->headLink()->appendStylesheet('/css/style.css');
?>
<title><?php 
echo $this->escape($this->title);
?>
</title>
</head>
<body>
<div id="pere">
	<div id="header">
		<div id="logo"></div>
		<div id="connect"><?php echo $this->action('login','index'); ?></div>
	</div>

	<?php 
	echo $this->layout()->content;
	?>
	
	<!-- <div id="footer"></div>  -->
</div>
</body>
</html>
