<?php echo $this->doctype('HTML5');?>
<html>
<head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
<?php 
$this->headLink()->appendStylesheet('/css/style.css');
$this->headScript()->prependFile('http://code.jquery.com/ui/1.8.24/jquery-ui.min.js');
$this->headScript()->prependFile('http://code.jquery.com/jquery-1.8.2.min.js');
echo $this->headScript();
echo $this->headLink();
?>
<title><?php echo $this->escape($this->title); ?>
</title>
</head>
<body>
	<div id="pere">
		<div id="header">
			<div id="logo"></div>
			<div id="connect">
				<?php echo $this->action('login','index'); ?>
			</div>
		</div>

		<div id="side_bar"></div>
		<nav>Navigation</nav>

		<?php echo $this->layout()->content; ?>

		<div id="footer">
			<p>Copyright INSSET Airlines - 2012</p>
		</div>
	</div>
</body>
</html>
