<script type="text/javascript">
function RechercheAeroport(provenance,pays)
{
$.ajax(
{
	type: "POST",
	url: "http://aeroport/Vol/rechercheaeroport",
	data: 'pays='+pays,
	success: function(msg)
	{
		if(provenance=='depart')
			{
			$('#aeroportDepart').empty();
			$('#aeroportDepart').append(msg);	
			}
		else if(provenance=='arrivee')
			{
			$('#aeroportArrivee').empty();
			$('#aeroportArrivee').append(msg);	
			}
	}
}
);
}
</script>