<table class="table_consulter-ligne">
	<thead>
		<tr id="TableHead">
			<?php 
			echo $this->Numero;
			echo $this->AeDepart;
			echo $this->AeArrive;
			echo $this->HeDepart;
			echo $this->HeArrivee;
			?>
		</tr>
	</thead>
	<tbody>
		<?php 
		$idLigne=0;
	foreach ($this->paginator as $ligne){ ?>
		<tr class="<?php echo $this->cycle(array("Odd", "Even"))->next();?>">
			<td class="ligne"><a
				href="<?php echo $this->baseUrl('vol/consulter-vol/ligne/').$ligne->numero_ligne; ?>"><?php echo $ligne->numero_ligne; ?>
			</a></td>
			<td class="ligne"><a
				href="<?php echo $this->baseUrl('vol/consulter-vol/ligne/').$ligne->numero_ligne; ?>"><?php echo $ligne->nom_aeroport_depart; ?>
			</a></td>
			<td class="ligne"><a
				href="<?php echo $this->baseUrl('vol/consulter-vol/ligne/').$ligne->numero_ligne; ?>"><?php echo $ligne->nom_aeroport_arrivee; ?>
			</a></td>
			<td class="ligne"><a
				href="<?php echo $this->baseUrl('vol/consulter-vol/ligne/').$ligne->numero_ligne; ?>"><?php echo $ligne->heure_depart; ?>
			</a></td>
			<td class="ligne"><a
				href="<?php echo $this->baseUrl('vol/consulter-vol/ligne/').$ligne->numero_ligne; ?>"><?php echo $ligne->heure_arrivee; ?>
			</a></td>
		</tr>

		<?php } ?>
	</tbody>
</table>
<?php 


echo $this->paginationControl($this->paginator, 'Sliding', 'pagination.phtml');

?>



