<?php 
foreach($this->messages as $message)
	echo $message;
?>
<h1>
	Informations sur la ligne
	<?php echo $this->ligne->numero_ligne;?>
</h1>
<fieldset>
	<legend>Informations détaillés sur la ligne</legend>
	<div class="infoLigne">
		<div class="infoLigneRow">
			<label for="numero">Numéro de la ligne :</label>
			<div class="" id="numero">
				<?php echo $this->ligne->numero_ligne; ?>
			</div>
		</div>
		<div class="infoLigneRow">
			<label for="aeroport_origine">Aéroport d'origine :</label>
			<div class="" id="aeroport_origine">
				<?php echo $this->aeroport_origine->nom." (".$this->villeOrigine->nom." / ".$this->paysOrigine->nom.")"; ?>
			</div>
		</div>
		<div class="infoLigneRow">
			<label for="aeroport_depart">Aéroport de départ :</label>
			<div class="" id="aeroport_depart">
				<?php echo $this->aeroport_depart->nom." (".$this->villeDepart->nom." / ".$this->paysDepart->nom.")"; ?>
			</div>
		</div>
		<div class="infoLigneRow">
			<label for="aeroport_arrive">Aéroport d'arrivé :</label>

			<div class="" id="aeroport_arrive">
				<?php echo $this->aeroport_arrivee->nom." (".$this->villeArrivee->nom." / ".$this->paysArrive->nom.")"; ?>
			</div>
		</div>
		<div class="infoLigneRow">
			<label for="heure_depart">Heure de départ :</label>
			<div class="" id="heure_depart">
				<?php 
				$heureDepart = new Zend_Date($this->ligne->heure_depart,'HH:mm:ss');
				echo $heureDepart->get('HH:mm');
				?>
			</div>
		</div>
		<div class="infoLigneRow">
			<label for="heure_arrivee">Heure d'arrivée :</label>
			<div class="" id="heure_arrivee">
				<?php 
				$heureArrivee = new Zend_Date($this->ligne->heure_arrivee,'HH:mm:ss');
				echo $heureArrivee->get('HH:mm');
				?>
			</div>
		</div>
		<?php if($this->nbJours>0){?>
		<div class="infoLigneRow">
			<label for="periodicite">Périodicité :</label>
			<div class="" id="periodicite">
				<?php 
				foreach($this->jours as $jour){
					?>
				<span class=""> <?php echo $jour->libelle; ?>
				</span>
				<?php } ?>
			</div>
		</div>
		<?php }?>
		<div class="infoLigneRow">
			<label for="tarif">Tarif : </label>
			<div class="" id="tarif">
				<?php echo $this->ligne->tarif." €";?>
			</div>
		</div>
		<div class="infoLigneRow">
			<label for="distance">Distance :</label>
			<div class="" id="distance">
				<?php echo $this->ligne->distance." km"; ?>
			</div>
		</div>

</fieldset>
<?php 
if(($this->count)>0)
{
	?>
<h2>Liste des vols</h2>
<table class="table_consulter-vol">
	<thead>
		<tr id="TableHead">
			<?php 
			echo $this->Id;
			echo $this->DaDepart;
			echo $this->DaArrive;
			echo $this->Avion;
			echo $this->Pilote;
			echo $this->Copilote;
			?>
		</tr>
	</thead>
	<tbody>
		<?php foreach($this->paginator as $vol){ ?>
		<tr class="<?php echo $this->cycle(array("Odd", "Even"))->next();?>">
			<td class="ligne"><a
				href="<?php echo $this->baseUrl('vol/fiche-vol/ligne/'.$vol->numero_ligne.'/vol/').$vol->id_vol; ?>"><?php echo $vol->id_vol ?>
			</a></td>
			<td class="ligne"><a
				href="<?php echo $this->baseUrl('vol/fiche-vol/ligne/'.$vol->numero_ligne.'/vol/').$vol->id_vol; ?>">
					<?php 
					$madate = strtotime($vol->date_depart);
					echo date("d/m/Y",$madate);
					?>
			</a></td>
			<td class="ligne"><a
				href="<?php echo $this->baseUrl('vol/fiche-vol/ligne/'.$vol->numero_ligne.'/vol/').$vol->id_vol; ?>"><?php 
				$madate = strtotime($vol->date_arrivee);
				echo date("d/m/Y",$madate);
				?> </a></td>
			<td class="ligne"><a
				href="<?php echo $this->baseUrl('vol/fiche-vol/ligne/'.$vol->numero_ligne.'/vol/').$vol->id_vol; ?>"><?php if ($vol->id_avion==NULL) echo "non affecté"; else echo $vol->libelle; ?>
			</a></td>
			<td class="ligne"><a
				href="<?php echo $this->baseUrl('vol/fiche-vol/ligne/'.$vol->numero_ligne.'/vol/').$vol->id_vol; ?>"><?php if ($vol->id_pilote==NULL) echo "non affecté"; else echo $vol->nom; ?>
			</a></td>
			<td class="ligne"><a
				href="<?php echo $this->baseUrl('vol/fiche-vol/ligne/'.$vol->numero_ligne.'/vol/').$vol->id_vol; ?>"><?php if ($vol->id_copilote==NULL) echo "non affecté"; else echo $vol->copilote; ?>
			</a></td>
		</tr>
		<?php
	} ?>
	</tbody>
</table>
<?php 
}
else {
	?>
<div class="noVols">Il n'y a pas de vols affectés a cette ligne</div>
<?php 
}
?>
<?php
echo $this->paginationControl($this->paginator, 'Sliding', 'pagination.phtml');
?>
