<?php 
foreach($this->messages as $message)
	echo $message;
?>
<?php 
$vol=$this->vol;
$ligne=$this->ligne;
$jours = array("1"=>"Lundi","2"=>"Mardi","3"=>"Mercredi","4"=>"Jeudi","5"=>"Vendredi","6"=>"Samedi","7"=>"Dimanche");
?>
<h1>
	Fiche du vol
	<?php echo $vol->id_vol;?>
</h1>
<div class="fiche-vol">
	<fieldset>
		<legend>Informations sur la ligne</legend>

		<div class="infoLigneRow">
			<label for="numero">Numéro de la ligne : </label>
			<div class="" id="numero">
				<?php echo $ligne->numero_ligne;?>
			</div>
		</div>
		<div class="infoLigneRow">
			<label for="aeroport_origine">Aéroport d'origine : </label>
			<div class="" id="aeroport_origine">
				<?php echo $this->aeroport_origine->nom." (".$this->villeOrigine->nom." / ".$this->paysOrigine->nom.")";?>
			</div>
		</div>
		<div class="infoLigneRow">
			<label for="aeroport_depart">Aéroport de départ : </label>
			<div class="" id="aeroport_depart">
				<?php echo $this->aeroport_depart->nom." (".$this->villeDepart->nom." / ".$this->paysDepart->nom.")";?>
			</div>
		</div>
		<div class="infoLigneRow">
			<label for="aeroport_arrive">Aéroport d'arrivé : </label>
			<div class="" id="aeroport_arrive">
				<?php echo $this->aeroport_arrivee->nom." (".$this->villeArrivee->nom." / ".$this->paysArrive->nom.")";?>
			</div>
		</div>
		<div class="infoLigneRow">
			<label for="heure_depart">Heure de départ : </label>
			<div class="" id="heure_depart">
				<?php 
				$heureDepart = new Zend_Date($ligne->heure_depart,'HH:mm:ss');
				echo $heureDepart->get('HH:mm');
				?>
			</div>
		</div>
		<div class="infoLigneRow">
			<label for="heure_arrivee">Heure d'arrivée : </label>
			<div class="" id="heure_arrivee">
				<?php 
				$heureDepart = new Zend_Date($ligne->heure_arrivee,'HH:mm:ss');
				echo $heureDepart->get('HH:mm');
				?>
			</div>
		</div>
		<div class="infoLigneRow">
			<label for="periodicite">Périodicité :</label>
			<div class="" id="periodicite">
				<?php if($this->nbJours>0){?>
				<?php 
				foreach($this->jours as $jour){
					?>
				<span class=""> <?php echo $jour->libelle; ?>
				</span>
				<?php } ?>
				<?php } else {?>
				Vol à la carte
				<?php } ?>
			</div>
		</div>
		<div class="infoLigneRow">
			<label for="tarif">Tarif : </label>
			<div class="" id="tarif">
				<?php echo $ligne->tarif." €";?>
			</div>
		</div>
		<div class="infoLigneRow">
			<label for="distance">Distance : </label>
			<div class="" id="distance">
				<?php echo $ligne->distance." km";?>
			</div>
		</div>
	</fieldset>
	<fieldset>
		<legend>Informations sur le vol</legend>
		<div class="infoVolRow">
			<label for="vol">Numero du vol : </label>
			<div class="" id="vol">
				<?php echo $vol->id_vol;?>
			</div>
		</div>
		<div class="infoVolRow">
			<label for="date_depart">Date de départ : </label>
			<div class="" id="date_depart">
				<?php 
				$madate = strtotime($vol->date_depart);
				echo "(".$jours[date("N",$madate)].") ".date("d/m/y",$madate);
				?>
			</div>
		</div>
		<div class="infoVolRow">
			<label for="date_arrivee">Date d'arrivée : </label>
			<div class="" id="date_arrivee">
				<?php 
				//echo $vol->date_arrivee;
				$madate = strtotime($vol->date_arrivee);
				echo "(".$jours[date("N",$madate)].") ".date("d/m/y",$madate);
				?>
			</div>
		</div>
		<div class="infoVolRow">
			<label for="type_avion">Type d'avion : </label>
			<div class="" id="type_avion">
				<?php if($vol->id_avion!=NULL) {
					echo $this->typeAvion->libelle;
				} else {
					echo "Non affecté";
						} ?>
			</div>
		</div>
		<div class="infoVolRow">
			<label for="pilote">Pilote : </label>
			<div class="" id="pilote">
				<?php if($vol->id_pilote!=NULL) {  
					echo strtoupper($this->pilote->nom).' '.$this->pilote->prenom;
				} else {
					echo "Non affecté";
						} ?>
			</div>
		</div>
		<div class="infoVolRow">
			<label for="copilote">Copilote : </label>
			<div class="" id="copilote">
				<?php if($vol->id_copilote!=NULL) {
					echo strtoupper($this->copilote->nom).' '.$this->copilote->prenom;
				} else {
					echo "Non affecté";
						} ?>
			</div>
		</div>
		<div class="infoVolRow">
			<label for="tarif">Tarif effectif : </label>
			<div class="" id="tarif">
				<?php echo $vol->tarif_effectif." €"; ?>
			</div>
		</div>
	</fieldset>
	<fieldset>
		<legend>Données Effectives</legend>
		<div class="infoEffRow">
			<label for="aeroport_depart_effectif">Aéroport de départ effectif : </label>
			<div class="" id="aeroport_depart_effectif">
				<?php echo $this->aeroport_depart_effectif->nom;?>
			</div>
		</div>
		<div class="infoEffRow">
			<label for="aeroport_arrivee_effectif">Aéroport d'arrivé effectif : </label>
			<div class="" id="aeroport_arrivee_effectif">
				<?php echo $this->aeroport_arrivee_effectif->nom;?>
			</div>
		</div>
		<div class="infoEffRow">
			<label for="heure_arrivee_effective">Heure d'arrivée effective : </label>
			<div class="" id="heure_arrivee_effective">
				<?php 
				if($vol->heure_arrivee_effective!=NULL) {
					$heureArriveeEffective = new Zend_Date($vol->heure_arrivee_effective,'HH:mm:ss');
					echo $heureArriveeEffective->get('HH:mm');
				}
				else
					echo "Non attribué";
				?>
			</div>
		</div>
	</fieldset>
</div>
